// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import { Logger, Result } from "@chili3d/core";
import type { CamMesh, CamOperationContext } from "../../model/operation";
import type { Vec3 } from "../../model/toolpath";
import {
    type BedPlacement,
    bedFitProblem,
    bedPlacement,
    type MeshBounds,
    meshBounds,
    weldMesh,
} from "../geometry/mesh";
import { firstLayerMargin } from "../slicer/slicer";
import { serializePrusaCommentedConfig, serializePrusaIni } from "./ini";
import { type PrusaJob, type PrusaJobSettings, resolvePrusaJob, serializePrusaOption } from "./library";
import { bedRectangle, configValue, readSlicerSettings } from "./settings";
import { firstNumber, formatNumber, parsePoints } from "./values";

/**
 * A PrusaSlicer project 3MF: the parts' welded meshes placed on the bed, plus
 * `Metadata/Slic3r_PE.config` (the merged print/filament/printer config, in the commented
 * form PrusaSlicer reads back) and `Metadata/Slic3r_PE_model.config` (object names and
 * per-object option overrides). Opening it in PrusaSlicer ("Open project") restores the
 * configured job; the same file is what the local bridge slices.
 *
 * Each object's mesh is stored centred on its own XY origin (z from the bed up) and placed by
 * its build item's transform, as PrusaSlicer writes its own projects.
 */

export interface PrusaProjectObject {
    readonly name: string;
    /** Triangles in the bed frame (WCS), mm. */
    readonly mesh: CamMesh;
    /** Per-object option overrides (PrusaSlicer keys). */
    readonly settings?: Readonly<Record<string, string | number | boolean>>;
}

export interface PrusaProjectOptions {
    readonly placement?: BedPlacement;
    readonly title?: string;
    /** Generator line date (default now). */
    readonly now?: Date;
}

export interface PrusaProject {
    /** Package part name → text content. */
    readonly files: Readonly<Record<string, string>>;
    /** How the objects were moved onto the bed. */
    readonly translation: Vec3;
    readonly objectCount: number;
    readonly triangleCount: number;
}

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
 <Default Extension="config" ContentType="text/plain"/>
</Types>
`;

const RELATIONSHIPS = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`;

export const escapeXml = (text: string) =>
    text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&apos;");

const num = (value: number) => formatNumber(value, 6);

function mergeBounds(boxes: readonly MeshBounds[]): MeshBounds | undefined {
    if (boxes.length === 0) return undefined;
    const min: [number, number, number] = [...boxes[0].min];
    const max: [number, number, number] = [...boxes[0].max];
    for (const box of boxes) {
        for (let k = 0; k < 3; k++) {
            min[k] = Math.min(min[k], box.min[k]);
            max[k] = Math.max(max[k], box.max[k]);
        }
    }
    return { min, max };
}

/** The generator line PrusaSlicer expects on top of its config files. */
export function generatorHeader(now = new Date()): string {
    return `generated by Chili3d on ${now.toISOString().slice(0, 10)} at ${now.toISOString().slice(11, 19)} UTC`;
}

/** The project's package parts (pure; `writePrusaProject` zips them). */
export function prusaProjectFiles(
    objects: readonly PrusaProjectObject[],
    job: PrusaJob,
    options: PrusaProjectOptions = {},
): Result<PrusaProject> {
    const welded = objects.map((object) => ({ object, mesh: weldMesh(object.mesh) }));
    const nonEmpty = welded.filter((entry) => entry.mesh.triangles.length > 0);
    if (nonEmpty.length === 0) return Result.err("nothing to export: the parts have no triangles");
    const boxes = nonEmpty.map((entry) => meshBounds(entry.mesh.vertices) as MeshBounds);
    const all = mergeBounds(boxes) as MeshBounds;
    const rect = bedRectangle(parsePoints(configValue(job.config, "bed_shape")));
    const bed = {
        min: rect.min,
        max: rect.max,
        maxHeight: firstNumber(configValue(job.config, "max_print_height"), 200),
    };
    const translation = bedPlacement(
        all,
        bed,
        options.placement,
        firstLayerMargin(readSlicerSettings(job.config)),
    );
    const placedAll: MeshBounds = {
        min: [all.min[0] + translation[0], all.min[1] + translation[1], 0],
        max: [all.max[0] + translation[0], all.max[1] + translation[1], all.max[2] + translation[2]],
    };
    const fit = bedFitProblem(placedAll, bed);
    if (fit) return Result.err(`cannot export: ${fit}`);

    const now = options.now ?? new Date();
    const model: string[] = [
        `<?xml version="1.0" encoding="UTF-8"?>`,
        `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">`,
        ` <metadata name="slic3rpe:Version3mf">1</metadata>`,
        ` <metadata name="Title">${escapeXml(options.title ?? nonEmpty[0].object.name)}</metadata>`,
        ` <metadata name="Application">Chili3d</metadata>`,
        ` <metadata name="CreationDate">${now.toISOString().slice(0, 10)}</metadata>`,
        ` <resources>`,
    ];
    const items: string[] = [];
    const modelConfig: string[] = [`<?xml version="1.0" encoding="UTF-8"?>`, `<config>`];
    let triangleCount = 0;
    nonEmpty.forEach(({ object, mesh }, i) => {
        const id = i + 1;
        const box = boxes[i];
        const cx = (box.min[0] + box.max[0]) / 2;
        const cy = (box.min[1] + box.max[1]) / 2;
        const v = mesh.vertices;
        model.push(`  <object id="${id}" type="model">`, `   <mesh>`, `    <vertices>`);
        for (let k = 0; k < v.length; k += 3) {
            model.push(
                `     <vertex x="${num(v[k] - cx)}" y="${num(v[k + 1] - cy)}" z="${num(v[k + 2] + translation[2])}"/>`,
            );
        }
        model.push(`    </vertices>`, `    <triangles>`);
        const t = mesh.triangles;
        for (let k = 0; k < t.length; k += 3) {
            model.push(`     <triangle v1="${t[k]}" v2="${t[k + 1]}" v3="${t[k + 2]}"/>`);
        }
        model.push(`    </triangles>`, `   </mesh>`, `  </object>`);
        const tx = cx + translation[0];
        const ty = cy + translation[1];
        items.push(
            `  <item objectid="${id}" transform="1 0 0 0 1 0 0 0 1 ${num(tx)} ${num(ty)} 0" printable="1"/>`,
        );
        const triangles = t.length / 3;
        triangleCount += triangles;
        const name = escapeXml(object.name);
        modelConfig.push(` <object id="${id}" instances_count="1">`);
        modelConfig.push(`  <metadata type="object" key="name" value="${name}"/>`);
        for (const [key, value] of Object.entries(object.settings ?? {})) {
            if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
            modelConfig.push(
                `  <metadata type="object" key="${key}" value="${escapeXml(serializePrusaOption(value))}"/>`,
            );
        }
        modelConfig.push(
            `  <volume firstid="0" lastid="${triangles - 1}">`,
            `   <metadata type="volume" key="name" value="${name}"/>`,
            `   <metadata type="volume" key="volume_type" value="ModelPart"/>`,
            `   <metadata type="volume" key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>`,
            `   <mesh edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>`,
            `  </volume>`,
            ` </object>`,
        );
    });
    model.push(` </resources>`, ` <build>`, ...items, ` </build>`, `</model>`, ``);
    modelConfig.push(`</config>`, ``);
    return Result.ok({
        files: {
            "[Content_Types].xml": CONTENT_TYPES,
            "_rels/.rels": RELATIONSHIPS,
            "3D/3dmodel.model": model.join("\n"),
            "Metadata/Slic3r_PE.config": serializePrusaCommentedConfig(job.config, generatorHeader(now)),
            "Metadata/Slic3r_PE_model.config": modelConfig.join("\n"),
        },
        translation,
        objectCount: nonEmpty.length,
        triangleCount,
    });
}

/** Zips project files into `.3mf` bytes. */
export async function zipProject(files: Readonly<Record<string, string>>): Promise<Uint8Array> {
    const { default: JSZip } = await import("jszip");
    const zip = new JSZip();
    for (const [name, content] of Object.entries(files)) zip.file(name, content);
    return zip.generateAsync({ type: "uint8array", compression: "DEFLATE" });
}

export async function writePrusaProject(
    objects: readonly PrusaProjectObject[],
    job: PrusaJob,
    options: PrusaProjectOptions = {},
): Promise<Result<Uint8Array>> {
    const project = prusaProjectFiles(objects, job, options);
    if (!project.isOk) return Result.err(project.error);
    return Result.ok(await zipProject(project.value.files));
}

function nodeName(context: CamOperationContext, id: string | undefined): string | undefined {
    if (id === undefined) return undefined;
    try {
        return context.document.modelManager.findNode((node) => node.id === id)?.name;
    } catch (error) {
        Logger.warn("CAM: cannot look up part names", error);
        return undefined;
    }
}

/**
 * The objects of a setup: one per part (from the parts' own triangulations, in WCS) when
 * there are several, else the setup's combined part mesh.
 */
export function prusaProjectObjects(
    context: CamOperationContext,
    settings: PrusaJobSettings = {},
): PrusaProjectObject[] {
    const names = settings.objectNames ?? [];
    const objectSettings = (i: number) => settings.objectSettings?.[i];
    if (context.parts.length > 1) {
        const objects: PrusaProjectObject[] = [];
        context.parts.forEach((part, i) => {
            const faces = part.mesh.faces;
            if (!faces || faces.index.length === 0) return;
            objects.push({
                name: names[i] ?? nodeName(context, context.setup.partIds[i]) ?? `Part ${i + 1}`,
                mesh: { positions: faces.position, indices: faces.index },
                settings: objectSettings(i),
            });
        });
        if (objects.length > 0) return objects;
    }
    return [
        {
            name: names[0] ?? nodeName(context, context.setup.partIds[0]) ?? context.setup.name,
            mesh: context.partMesh(),
            settings: objectSettings(0),
        },
    ];
}

/**
 * The CAM Studio's "Open in PrusaSlicer" action: the setup's parts and the job's presets as a
 * PrusaSlicer project 3MF. Rejects (with a message) when the machine is not a printer, the
 * parts are empty or they do not fit the printer.
 */
export async function exportPrusaProject(
    context: CamOperationContext,
    settings: PrusaJobSettings = {},
): Promise<Uint8Array> {
    const job = resolvePrusaJob(context.machine, settings);
    if (!job.isOk) throw new Error(job.error);
    const bytes = await writePrusaProject(prusaProjectObjects(context, settings), job.value, {
        placement: settings.placement,
        title: context.setup.programName ?? context.setup.name,
    });
    if (!bytes.isOk) throw new Error(bytes.error);
    return bytes.value;
}

/** The plain INI the bridge passes to `prusa-slicer --load`. */
export function prusaJobIni(job: PrusaJob, now = new Date()): string {
    return serializePrusaIni(job.config, generatorHeader(now));
}
