// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import { looksLikeNcProgram } from "@chili3d/core";
import {
    detectNcDialect,
    type MachineProfileData,
    type NcProgram,
    readNcProgram,
    type ToolpathMove,
} from "../../src";

/**
 * Hand-written programs in the style of what real CAM systems and slicers produce: a
 * Fusion-style Fanuc program, a Mastercam-style inch program, LinuxCNC with o-word
 * subroutines, GRBL from a hobby CAM, a Siemens ISO program and PrusaSlicer output.
 */

const moves = (program: NcProgram): ToolpathMove[] =>
    program.toolpaths.flatMap((path) => path.toolpath.moves).filter((move) => move.kind !== "comment");
const warnings = (program: NcProgram) =>
    program.diagnostics.filter((d) => d.severity !== "info").map((d) => d.message);

const FUSION_FANUC = `%
O1001 (BRACKET)
(Using high feed G1 F5000. instead of G0.)
(T1  D=10. CR=0. - ZMIN=-2. - FLAT END MILL)
(T2  D=6.8 CR=0. TAPER=118DEG - ZMIN=-20. - DRILL)
N10 G90 G94 G17
N15 G21
N20 G53 G0 Z0.
(2D CONTOUR1)
N25 T1 M6
N30 S8000 M3
N35 G54
N40 M8
N45 G0 X-5.5 Y-5.5
N50 G43 Z15. H1
N55 G0 Z5.
N60 G1 Z-2. F333.3
N65 X0. F1000.
N70 G3 X5.5 Y0. I0. J5.5
N75 G1 Y40.
N80 G2 X15.5 Y50. I10. J0.
N85 G1 X60.
N90 G0 Z15.
N95 M9
N100 G53 G0 Z0.
(DRILL1)
N105 M1
N110 T2 M6
N115 S2400 M3
N120 G54
N125 M8
N130 G0 X20. Y20.
N135 G43 Z15. H2
N140 G0 Z5.
N145 G98 G83 X20. Y20. Z-20. R5. Q3. F240.
N150 X40.
N155 G80
N160 Z15.
N165 M9
N170 G53 G0 Z0.
N175 M5
N180 G53 G0 X0. Y0.
N185 M30
%
`;

const MASTERCAM_INCH = `%
O0100(PART1)
(PROGRAM NAME - PART1)
(DATE=DD-MM-YY - 07-10-26 TIME=HH:MM - 10:00)
(MATERIAL - ALUMINUM INCH - 2024)
( T1 |  1/4 FLAT ENDMILL | H1 )
N100 G20
N102 G0 G17 G40 G49 G80 G90
N104 T1 M6
N106 G0 G90 G54 X1.5 Y-.25 A0. S5000 M3
N108 G43 H1 Z.1
N110 G1 Z-.05 F10.
N112 Y0. F20.
N114 G2 X1.75 Y.25 R.25
N116 G1 X2.5
N118 G0 Z.1
N120 M5
N122 G91 G28 Z0.
N124 G28 X0. Y0. A0.
N126 M30
%
`;

const LINUXCNC_SUBS = `%
(MSG, holes on a bolt circle)
#<_safe_z> = 5
#<_depth> = -3
o<peck> sub
  G0 X#1 Y#2
  G0 Z#<_safe_z>
  G1 Z#<_depth> F120
  G0 Z#<_safe_z>
o<peck> endsub
G21 G90 G64 P0.01
T3 M6 G43 H3
S6000 M3
#<i> = 0
o100 while [#<i> LT 4]
  o<peck> call [20 * COS[#<i> * 90]] [20 * SIN[#<i> * 90]]
  #<i> = [#<i> + 1]
o100 endwhile
M5
M2
%
`;

const GRBL_HOBBY = `(Generated by a hobby CAM)
G90
G21
G0Z5.000
G0X0.000Y0.000
M3S18000
G1Z-1.000F300.0
G1X50.000F1000.0
G2X60.000Y10.000I0.000J10.000
G1Y30.000
G0Z5.000
M5
M30
`;

const SIEMENS_ISO = `; ROUGHING
N10 G17 G90 G40 G71 G94
N20 T1
N30 M6
N40 D1
N50 S3000 M3
N60 MSG("ROUGHING")
N70 G0 X0 Y0
N80 Z5
N90 G1 Z-2 F100
N100 G1 X10 Y0 F400
N110 G2 X20 Y10 CR=10
N120 G3 X30 Y20 I=AC(30) J=AC(10)
N130 G4 F1.5
N140 G0 Z50
N150 M30
`;

const PRUSASLICER = `; generated by PrusaSlicer 2.7.1+linux-x64-GTK3 on 2026-10-07 at 10:00:00 UTC
;
; external perimeters extrusion width = 0.45mm
M73 P0 R10
M201 X4000 Y4000 Z200 E2500
M862.3 P "MK4" ; printer model check
M862.1 P0.4 ; nozzle check
M115 U5.1.2+13478
M555 X72.5 Y73 W105 H104
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set bed temp
M104 T0 S170 ; set extruder temp for bed leveling
M109 T0 R170 ; wait for temp
M84 E ; turn off E motor
G28 ; home all without mesh bed level
G1 Z5 F720
G29 P1 ; invalidate mbl & probe print area
G29 A ; activate mbl
M104 S215
M190 S60
M109 S215
G92 E0
G1 X10 Y-4 Z0.2 F3000
G1 E2 F2400 ; deretraction
G1 X60 E9 F1000 ; purge
G1 E-0.8 F2100
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G92 E0.0
G1 Z.2 F720
G1 X76.473 Y75.846
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1800
G1 X77.334 Y75.225 E.03345
G2 X78.312 Y74.567 I-1.06 J-2.65 E.04
G1 X80 Y74 E.05
;LAYER_CHANGE
;Z:0.4
G1 Z.4 F720
G1 X81 Y74 E.04 F1800
M107
; filament used [mm] = 12.34
; estimated printing time (normal mode) = 1m 2s
`;

describe("dialect detection", () => {
    test.each([
        ["Fusion-style Fanuc", FUSION_FANUC, "fanuc"],
        ["Mastercam-style Fanuc", MASTERCAM_INCH, "fanuc"],
        ["LinuxCNC with o-words", LINUXCNC_SUBS, "linuxcnc"],
        ["GRBL", GRBL_HOBBY, "grbl"],
        ["Siemens", SIEMENS_ISO, "siemens"],
        ["PrusaSlicer", PRUSASLICER, "prusa"],
        [
            "Haas",
            "%\nO01234 (HAAS VF2)\nT1 M06\nG187 P1\nS5000 M03\nG00 G54 X0 Y0\nG53 G00 Z0.\nM30\n%",
            "haas",
        ],
        ["Klipper", "; generated by OrcaSlicer 2.1\nPRINT_START BED=60\nG1 X10 Y10 E1 F1200\n", "klipper"],
        [
            "Marlin (Cura)",
            ";FLAVOR:Marlin\n;Generated with Cura_SteamEngine 5.4.0\nM104 S200\nG1 X10 E1\n",
            "marlin",
        ],
        [
            "Heidenhain",
            "0 BEGIN PGM PART MM\n1 TOOL CALL 1 Z S5000\n2 L X+0 Y+0 R0 FMAX\n3 END PGM PART MM\n",
            "heidenhain",
        ],
        [
            "laser (GRBL laser mode)",
            "(Laser mode: set $32=1)\nG90 G21\nG0 X0 Y0\nM4 S800\nG1 X10 F1500\nM5\n",
            "laser",
        ],
    ])("%s", (_name, text, dialect) => {
        expect(detectNcDialect(text)).toBe(dialect);
    });
});

describe("looksLikeNcProgram (files whose name does not say)", () => {
    test.each([
        ["a Fanuc program", FUSION_FANUC, true],
        ["packed GRBL", GRBL_HOBBY, true],
        ["printer G-code", PRUSASLICER, true],
        ["Heidenhain", "0 BEGIN PGM PART MM\n1 END PGM PART MM\n", true],
        ["Markdown about G-code", "# Notes\n\nUse `G1 X10` to move.\n\n- G0 is rapid\n- G1 is feed\n", false],
        ["a CSV table", "x,y,z\n1,2,3\n4,5,6\n7,8,9\n", false],
        ["prose", "The quick brown fox\njumps over\nthe lazy dog\n", false],
    ])("%s", (_name, text, expected) => {
        expect(looksLikeNcProgram(text)).toBe(expected);
    });
});

describe("real-world programs", () => {
    test("a Fusion-style Fanuc program: tools from the header, labels, cycles, stops, reference moves", () => {
        const program = readNcProgram(FUSION_FANUC);
        expect(program.dialect).toBe("fanuc");
        expect(program.detected).toBe(true);
        expect(program.programNumber).toBe("1001");
        expect(program.name).toBe("BRACKET");
        expect(program.tools.map((tool) => [tool.number, tool.diameter])).toEqual([
            [1, 10],
            [2, 6.8],
        ]);
        expect(program.toolpaths.map((path) => [path.toolNumber, path.toolpath.label])).toEqual([
            [1, "2D CONTOUR1"],
            [2, "DRILL1"],
        ]);
        const all = moves(program);
        expect(all.filter((move) => move.kind === "arc")).toHaveLength(2);
        expect(
            all.filter((move) => move.kind === "drill").map((move) => (move.kind === "drill" ? move.at : [])),
        ).toEqual([
            [20, 20, 5],
            [40, 20, 5],
        ]);
        // M1 before the tool change is an (optional) stop.
        expect(all.some((move) => move.kind === "dwell" && move.seconds === 0)).toBe(true);
        expect(warnings(program)).toEqual([]);
        // G53 G0 Z0. returns to the reference height, drawn at the highest programmed Z (where
        // the program already is); X/Y homing is reported, not drawn.
        expect(program.stats.bounds?.max[2]).toBe(15);
        expect(program.diagnostics.map((d) => d.message)).toContain(
            "X/Y reference positions are unknown in the work offset: X and Y are left where they are",
        );
        expect(program.stats.cutBounds).toEqual({ min: [-5.5, -5.5, -20], max: [60, 50, 5] });
    });

    test("a Mastercam-style inch program: leading-dot numbers, R arcs, G28 in two steps", () => {
        const program = readNcProgram(MASTERCAM_INCH);
        expect(program.units).toBe("inch");
        const arc = moves(program).find((move) => move.kind === "arc") as Extract<
            ToolpathMove,
            { kind: "arc" }
        >;
        expect(arc.to[0]).toBeCloseTo(1.75 * 25.4, 9);
        expect(arc.center[0]).toBeCloseTo(1.75 * 25.4, 9);
        expect(arc.center[1]).toBeCloseTo(0, 9);
        expect(arc.feed).toBeCloseTo(20 * 25.4, 9);
        expect(program.toolpaths[0].toolpath.spindleRpm).toBe(5000);
        expect(warnings(program)).toEqual([]);
    });

    test("LinuxCNC: named parameters, o-word subroutine called in a while loop", () => {
        const program = readNcProgram(LINUXCNC_SUBS);
        expect(program.dialect).toBe("linuxcnc");
        const plunges = moves(program).filter((move) => move.kind === "linear");
        expect(plunges).toHaveLength(4);
        const round = (value: number) => Math.round(value) + 0;
        const holes = plunges.map((move) =>
            "to" in move ? [round(move.to[0]), round(move.to[1]), move.to[2]] : [],
        );
        expect(holes).toEqual([
            [20, 0, -3],
            [0, 20, -3],
            [-20, 0, -3],
            [0, -20, -3],
        ]);
        expect(program.toolpaths[0].toolNumber).toBe(3);
        expect(warnings(program)).toEqual([]);
    });

    test("GRBL from a hobby CAM: packed words, no tool changer", () => {
        const program = readNcProgram(GRBL_HOBBY);
        expect(program.dialect).toBe("grbl");
        // G0X0Y0 after G0Z5 from an unknown start lands where the first rapid assumed (X0 Y0).
        expect(moves(program).map((move) => move.kind)).toEqual([
            "rapid",
            "linear",
            "linear",
            "arc",
            "linear",
            "rapid",
        ]);
        expect(program.toolpaths[0].toolNumber).toBe(0);
        expect(program.stats.spindle).toEqual({ min: 18000, max: 18000 });
        expect(warnings(program)).toEqual([]);
    });

    test("Siemens: CR= radius, AC() centres, G4 F seconds, MSG", () => {
        const program = readNcProgram(SIEMENS_ISO);
        expect(program.dialect).toBe("siemens");
        const arcs = moves(program).filter((move) => move.kind === "arc") as Extract<
            ToolpathMove,
            { kind: "arc" }
        >[];
        expect(arcs.map((arc) => [arc.center[0], arc.center[1], arc.clockwise])).toEqual([
            // CR > 0: the short way round, clockwise from (10, 0) to (20, 10).
            [expect.closeTo(20, 9), expect.closeTo(0, 9), true],
            [30, 10, false],
        ]);
        expect(moves(program)).toContainEqual({ kind: "dwell", seconds: 1.5 });
        expect(program.toolpaths[0].toolpath.moves).toContainEqual({ kind: "comment", text: "ROUGHING" });
        expect(warnings(program)).toEqual([]);
    });

    test("PrusaSlicer output: firmware codes ignored, extrusion and layers read", () => {
        const program = readNcProgram(PRUSASLICER);
        expect(program.dialect).toBe("prusa");
        expect(program.machineKind).toBe("printer");
        expect(program.stats.layers).toBe(2);
        expect(program.stats.filament).toBeCloseTo(2 + 9 - 0.8 + 0.8 + 0.03345 + 0.04 + 0.05 + 0.04, 6);
        expect(warnings(program)).toEqual([]);
        // The arc with extrusion is drawn as extruding segments.
        const extrudes = moves(program).filter((move) => move.kind === "extrude");
        expect(extrudes.length).toBeGreaterThan(8);
    });
});

describe("statistics", () => {
    const machine: MachineProfileData = {
        id: "m",
        name: "Mill",
        kind: "mill",
        linearAxes: [],
        maxFeed: 600,
        rapidFeed: 6000,
        post: { id: "fanuc" },
    };

    test("lengths at their true length, times at the machine's limits", () => {
        const program = readNcProgram(
            ["G0 X0 Y0 Z10", "G0 Z0", "G1 X100 F1200", "G3 X100 Y20 I0 J10", "G4 P2000", "G0 Z10"].join("\n"),
            { machine },
        );
        const { stats } = program;
        expect(stats.rapidLength).toBeCloseTo(20, 9);
        expect(stats.cuttingLength).toBeCloseTo(100 + Math.PI * 10, 9);
        // Feeds capped at the machine's 600 mm/min, rapids at 6000.
        expect(stats.cuttingTime).toBeCloseTo(((100 + Math.PI * 10) / 600) * 60, 9);
        expect(stats.rapidTime).toBeCloseTo((20 / 6000) * 60, 9);
        expect(stats.dwellTime).toBe(2);
        expect(stats.totalTime).toBeCloseTo(stats.cuttingTime + stats.rapidTime + 2, 9);
        expect(stats.timeAssumed).toBe(false);
        // The arc bulges to X110: bounds follow arcs, not only their end points.
        expect(stats.bounds).toEqual({ min: [0, 0, 0], max: [110, 20, 10] });
        expect(stats.feed).toEqual({ min: 1200, max: 1200 });
    });
});
