// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import {
    type CamProgram,
    clearanceHeight,
    contourOperation,
    detectNcDialect,
    dialectOfPost,
    type MachineProfileData,
    machineProfile,
    moveEnd,
    type NcProgram,
    pocketOperation,
    postProcessor,
    postProcessors,
    profileCutOperation,
    readNcProgram,
    type SetupData,
    type ToolData,
    type ToolpathData,
    wireContourOperation,
} from "../../src";
import {
    GENERIC_AC_TRUNNION,
    GENERIC_AC_TRUNNION_NON_TCP,
    GENERIC_BC_HEAD_TABLE,
    GENERIC_CA_HEAD_HEAD,
} from "../../src/ops5x/machines";
import { circleLoop, fakeContext, millTool, operation, rectLoop } from "../_helpers/context";
import { expectSameToolpaths, type RoundTripOptions, toolSequence } from "../_helpers/ncRoundTrip";
import { program as fiveAxisProgram } from "../ops5x/postFixture";

/**
 * Conformance by round trip: toolpaths — generated by the CAM operations or built by hand —
 * posted with every registered post, read back with the NC reader, and compared move for
 * move (see `_helpers/ncRoundTrip.ts`): arcs and helices, drilling cycles canned or
 * expanded, tool changes, dwells and stops, 5-axis tool axes through each machine's
 * kinematics, beam on/off with pierce delays, wire tapers, extrusion.
 */

const SETUP: SetupData = {
    id: "s1",
    name: "Setup 1",
    machineId: "test",
    wcs: { origin: [0, 0, 0], xAxis: [1, 0, 0], zAxis: [0, 0, 1] },
    stock: { kind: "box", margin: { x: 1, y: 1, zTop: 1, zBottom: 0 } },
    partIds: [],
    operations: [],
};

function camProgram(machine: MachineProfileData, toolpaths: ToolpathData[], tools: ToolData[]): CamProgram {
    return {
        name: "Part",
        machine,
        setup: SETUP,
        tools: new Map(tools.map((tool) => [tool.id, tool])),
        toolpaths,
    };
}

function ok<T>(result: { isOk: boolean; value?: T; error?: string } | Promise<unknown>): T {
    if (!("isOk" in result)) throw new Error("expected a synchronous result");
    if (!result.isOk) throw new Error(result.error);
    return result.value as T;
}

function post(id: string, program: CamProgram, options?: Record<string, unknown>): string {
    const processor = postProcessor(id);
    expect(processor).not.toBeUndefined();
    return ok(processor!.post(program, options));
}

// ------------------------------------------------------------------ Mills (3-axis)

const MILL: MachineProfileData = {
    id: "test-mill",
    name: "Test mill",
    kind: "mill",
    linearAxes: [
        { name: "X", min: -500, max: 500 },
        { name: "Y", min: -400, max: 400 },
        { name: "Z", min: -400, max: 0 },
    ],
    maxFeed: 10000,
    rapidFeed: 20000,
    post: { id: "fanuc" },
};

const ENDMILL = millTool(6, {
    id: "em6",
    number: 1,
    cutting: { feed: 1000, plungeFeed: 300, spindleRpm: 10000, stepdown: 3, coolant: "flood" },
});
const BALL: ToolData = {
    id: "ball3",
    number: 4,
    name: "3 mm ball",
    kind: "ballEndmill",
    diameter: 3,
    cutting: { spindleRpm: 15000, feed: 800, coolant: "mist" },
};
const DRILL: ToolData = {
    id: "drill5",
    number: 2,
    name: "5 mm drill",
    kind: "drill",
    diameter: 5,
    tipAngle: 118,
    cutting: { spindleRpm: 2000, feed: 150, coolant: "flood" },
};
const TAP: ToolData = {
    id: "tapM6",
    number: 3,
    name: "M6 tap",
    kind: "tap",
    diameter: 6,
    pitch: 1,
    cutting: { spindleRpm: 500, feed: 500 },
};

function generated(handler: typeof pocketOperation, params: Record<string, unknown>): ToolpathData {
    const outer = rectLoop(0, 0, 40, 30);
    const island = circleLoop([20, 15], 5, 0.001, false);
    return ok(
        handler.generate(
            operation(handler.type, params),
            fakeContext({
                tool: ENDMILL,
                loops: [
                    { points: outer, closed: true, role: "sketch", z: -4 },
                    { points: island, closed: true, role: "sketch", z: -4 },
                ],
                stock: { min: [-5, -5, -10], max: [45, 35, 0] },
            }),
        ),
    );
}

const POCKET = {
    ...generated(pocketOperation, { strategy: "offset", stepover: 40, stepdown: 2 }),
    label: "Pocket",
};
const CONTOUR = { ...generated(contourOperation, { side: "outside", stepdown: 2 }), label: "Contour" };

const ARCS: ToolpathData = {
    toolId: "ball3",
    label: "Arcs",
    moves: [
        { kind: "rapid", to: [60, 0, 10] },
        { kind: "rapid", to: [60, 0, 2] },
        { kind: "linear", to: [60, 0, 0], feed: 200 },
        // A helix down one full turn, then a full circle at the bottom.
        { kind: "arc", to: [60, 0, -2], center: [55, 0, 0], clockwise: false, plane: "XY", feed: 600 },
        { kind: "arc", to: [60, 0, -2], center: [55, 0, -2], clockwise: true, plane: "XY", feed: 800 },
        // Arcs in the side planes.
        { kind: "linear", to: [60, 10, -2], feed: 800 },
        { kind: "arc", to: [64, 10, -6], center: [64, 10, -2], clockwise: true, plane: "ZX", feed: 500 },
        { kind: "arc", to: [64, 14, -2], center: [64, 10, -2], clockwise: false, plane: "YZ", feed: 500 },
        { kind: "dwell", seconds: 1.5 },
        { kind: "linear", to: [70, 14, -2], feed: 800 },
        { kind: "dwell", seconds: 0 },
        { kind: "rapid", to: [70, 14, 10] },
    ],
};

const DRILLING: ToolpathData = {
    toolId: "drill5",
    label: "Holes",
    moves: [
        { kind: "rapid", to: [10, -20, 15] },
        { kind: "drill", at: [10, -20, 0], depth: 8, retract: 2, cycle: "drill", feed: 150 },
        { kind: "drill", at: [20, -20, 0], depth: 8, retract: 2, cycle: "drill", feed: 150 },
        { kind: "drill", at: [30, -20, -1], depth: 5, retract: 1, cycle: "drill", dwell: 0.5, feed: 120 },
        { kind: "drill", at: [40, -20, 0], depth: 12, retract: 2, cycle: "peck", peck: 3, feed: 150 },
        { kind: "drill", at: [50, -20, 0], depth: 9, retract: 2, cycle: "chipBreak", peck: 2, feed: 150 },
        { kind: "drill", at: [60, -20, 0], depth: 6, retract: 3, cycle: "bore", feed: 100 },
        { kind: "rapid", to: [60, -20, 15] },
    ],
};

const TAPPING: ToolpathData = {
    toolId: "tapM6",
    label: "Tap",
    moves: [
        { kind: "rapid", to: [10, -20, 15] },
        { kind: "drill", at: [10, -20, 0], depth: 8, retract: 5, cycle: "tap", feed: 500 },
        { kind: "drill", at: [20, -20, 0], depth: 8, retract: 5, cycle: "tap", feed: 500 },
        { kind: "rapid", to: [20, -20, 15] },
    ],
};

const MILL_PATHS = [POCKET, CONTOUR, ARCS, DRILLING, TAPPING];
const MILL_PROGRAM = camProgram(MILL, MILL_PATHS, [ENDMILL, BALL, DRILL, TAP]);
const MILL_TOOLS = [1, 4, 2, 3];

/**
 * A toolpath with a new tool as a manual-change program says it: retract to the program's
 * clearance height (the post's way without a Z home), then a stop.
 */
function stopAtToolChange(path: ToolpathData, index: number, paths: readonly ToolpathData[]): ToolpathData {
    if (index === 0 || paths[index - 1].toolId === path.toolId) return path;
    const last = paths[index - 1].moves
        .map(moveEnd)
        .filter((end) => end !== undefined)
        .at(-1)!;
    const clearance = clearanceHeight(paths);
    return {
        ...path,
        moves: [
            { kind: "rapid", to: [last[0], last[1], Math.max(last[2], clearance)] },
            { kind: "dwell", seconds: 0 },
            ...path.moves,
        ],
    };
}

function readBack(text: string, postId: string, machine?: MachineProfileData): NcProgram {
    const program = readNcProgram(text, {
        dialect: dialectOfPost(postId),
        ...(machine === undefined ? {} : { machine }),
    });
    const errors = program.diagnostics.filter((d) => d.severity === "error");
    expect(errors).toEqual([]);
    return program;
}

describe("round trip through the mill posts", () => {
    const millPosts = postProcessors("mill").filter((p) =>
        ["fanuc", "haas", "linuxcnc", "mach3", "grbl"].includes(p.id),
    );

    test("every 3-axis mill post is covered", () => {
        expect(millPosts.map((p) => p.id).sort()).toEqual(["fanuc", "grbl", "haas", "linuxcnc", "mach3"]);
    });

    const cases = millPosts.flatMap((p) =>
        [
            {},
            { arcs: "r" },
            { arcs: "linear" },
            { cannedCycles: false },
            { lineNumbers: true, comments: false },
        ].map((options) => [p.id, options] as const),
    );

    test.each(cases)("%s %j", (postId, options) => {
        const text = post(postId, MILL_PROGRAM, options);
        expect(detectNcDialect(text)).toBe(dialectOfPost(postId));
        const read = readBack(text, postId);
        // GRBL has no tool changer: a change is a stop (M0) after a "Tool change: Tn" comment, so
        // without comments it is only the stop, and the tool in the spindle is never named (0).
        const manual = postId === "grbl";
        const silent = manual && "comments" in options && options.comments === false;
        const expectedPaths = silent ? MILL_PATHS.map(stopAtToolChange) : MILL_PATHS;
        // R-format arcs near a half circle put the centre within ~0.01 of where it was (R has 3–4 decimals).
        expectSameToolpaths(
            expectedPaths,
            read,
            "arcs" in options && options.arcs === "r" ? { tolerance: 0.01 } : {},
        );
        const expectedTools = silent ? [0] : manual ? [0, ...MILL_TOOLS.slice(1)] : MILL_TOOLS;
        expect(toolSequence(read.toolpaths.map((path) => path.toolNumber))).toEqual(expectedTools);
        expect(read.units).toBe("mm");
        expect(read.stats.cuttingLength).toBeGreaterThan(100);
    });

    test("drilling cycles come back as drill moves where the control runs them", () => {
        const read = readBack(post("fanuc", MILL_PROGRAM), "fanuc");
        const drills = read.toolpaths
            .flatMap((path) => path.toolpath.moves)
            .filter((move) => move.kind === "drill");
        expect(drills.map((move) => move.cycle)).toEqual([
            "drill",
            "drill",
            "drill",
            "peck",
            "chipBreak",
            "bore",
            "tap",
            "tap",
        ]);
        // The hole top is the R plane: the program does not say where material starts.
        expect(drills[3]).toEqual({
            kind: "drill",
            at: [40, -20, 2],
            depth: 14,
            retract: 2,
            cycle: "peck",
            peck: 3,
            feed: 150,
        });
    });

    test("spindle speeds and coolant follow each tool", () => {
        const read = readBack(post("haas", MILL_PROGRAM), "haas");
        expect(
            read.toolpaths.map((path) => [path.toolNumber, path.toolpath.spindleRpm, path.toolpath.coolant]),
        ).toEqual([
            [1, 10000, "flood"],
            [4, 15000, "mist"],
            [2, 2000, "flood"],
            [3, 500, undefined],
        ]);
        expect(read.stats.spindle).toEqual({ min: 500, max: 15000 });
        expect(read.stats.tools).toEqual([1, 4, 2, 3]);
        expect(read.stats.toolChanges).toBe(3);
    });
});

// ------------------------------------------------------------------ 5-axis

describe("round trip through the 5-axis posts", () => {
    const fiveAxis = postProcessors("mill").filter(
        (p) => !["fanuc", "haas", "linuxcnc", "mach3", "grbl"].includes(p.id),
    );

    test("every 5-axis post is covered", () => {
        expect(fiveAxis.map((p) => p.id).sort()).toEqual([
            "fanuc-30i-5axis",
            "generic-5axis-nontcp",
            "haas-umc-5axis",
            "heidenhain-tnc-5axis",
            "siemens-840d-5axis",
        ]);
    });

    test.each([
        ["fanuc-30i-5axis", GENERIC_AC_TRUNNION, {}, {}],
        ["fanuc-30i-5axis", GENERIC_CA_HEAD_HEAD, {}, {}],
        ["fanuc-30i-5axis", GENERIC_BC_HEAD_TABLE, {}, {}],
        ["haas-umc-5axis", GENERIC_AC_TRUNNION, {}, {}],
        ["siemens-840d-5axis", GENERIC_AC_TRUNNION, {}, {}],
        ["siemens-840d-5axis", GENERIC_CA_HEAD_HEAD, {}, {}],
        ["siemens-840d-5axis", GENERIC_CA_HEAD_HEAD, { orientation: "vector" }, {}],
        [
            "generic-5axis-nontcp",
            GENERIC_AC_TRUNNION_NON_TCP,
            { tolerance: 0.05, maxAngleStep: 30 },
            { ignoreFeed: true, tolerance: 0.06 },
        ],
    ] as const)("%s on %s", (postId, machine, options, compare: RoundTripOptions) => {
        const program = fiveAxisProgram(machine);
        const text = post(postId, program, options);
        expect(detectNcDialect(text)).toBe(dialectOfPost(postId));
        const read = readBack(text, postId, machine);
        expectSameToolpaths(program.toolpaths, read, { tolerance: 0.002, ...compare });
        const axes = read.toolpaths
            .flatMap((path) => path.toolpath.moves)
            .filter((move) => "axis" in move && move.axis !== undefined);
        expect(axes.length).toBeGreaterThan(3);
    });

    test("Heidenhain conversational is recognized and refused", () => {
        const text = post("heidenhain-tnc-5axis", fiveAxisProgram(GENERIC_BC_HEAD_TABLE));
        expect(detectNcDialect(text)).toBe("heidenhain");
        const read = readNcProgram(text);
        expect(read.dialect).toBe("heidenhain");
        expect(read.toolpaths).toEqual([]);
        expect(read.diagnostics).toEqual([
            expect.objectContaining({ severity: "error", message: expect.stringContaining("not supported") }),
        ]);
    });

    test("without a machine profile rotary words are reported and the tool stays vertical", () => {
        const text = post("fanuc-30i-5axis", fiveAxisProgram(GENERIC_AC_TRUNNION));
        const read = readNcProgram(text);
        expect(read.diagnostics.map((d) => d.message)).toEqual(
            expect.arrayContaining([expect.stringContaining("without a machine profile")]),
        );
        const tilted = read.toolpaths
            .flatMap((path) => path.toolpath.moves)
            .filter((move) => "axis" in move && move.axis !== undefined);
        // Only the tilted plane (G68.2 + G53.1) still orients the tool: the plane says so itself.
        expect(tilted.every((move) => "axis" in move && Math.abs(move.axis![1] - 0.5) < 1e-3)).toBe(true);
    });
});

// ------------------------------------------------------------------ 2D cutting

const SHEET = {
    min: [-50, -50, -6] as [number, number, number],
    max: [250, 150, 0] as [number, number, number],
};

function cuttingPaths(kind: "plasma" | "waterjet" | "laser"): {
    machine: MachineProfileData;
    paths: ToolpathData[];
    tool: ToolData;
} {
    const tool: ToolData = {
        id: "jet",
        number: 1,
        name: "Jet",
        kind: "jet",
        diameter: 1.5,
        cutting: { feed: 3000 },
    };
    const context = fakeContext({
        machine: { kind, cutting: { kerf: 1.5, pierceDelay: 0.5, pierceHeight: 3.8, cutHeight: 1.5 } },
        tool,
        loops: [
            { points: rectLoop(0, 0, 80, 50), closed: true, role: "sketch", z: 0 },
            { points: circleLoop([40, 25], 10, 0.001, false), closed: true, role: "sketch", z: 0 },
        ],
        stock: SHEET,
        setupStock: { kind: "sheet", width: 300, height: 200, thickness: 6 },
    });
    const path = ok<ToolpathData>(profileCutOperation.generate(operation("profileCut", {}), context));
    return { machine: context.machine, paths: [{ ...path, label: "Profile" }], tool };
}

describe("round trip through the cutting posts", () => {
    const posts = postProcessors().filter((p) =>
        p.machineKinds.some((kind) => ["plasma", "waterjet", "laser"].includes(kind)),
    );

    test("every cutting post is covered", () => {
        expect(posts.map((p) => p.id).sort()).toEqual(["laser-generic", "laser-grbl", "plasma", "waterjet"]);
    });

    test.each(
        posts.flatMap((p) => [[p.id, false] as const, [p.id, true] as const]),
    )("%s (Z out: %s)", (postId, outputZ) => {
        const kind = postProcessor(postId)!.machineKinds[0] as "plasma" | "waterjet" | "laser";
        const { machine, paths, tool } = cuttingPaths(kind);
        const text = post(postId, camProgram(machine, paths, [tool]), { outputZ });
        const read = readBack(text, postId, machine);
        expectSameToolpaths(paths, read, { xyOnly: !outputZ });
        const ons = read.toolpaths
            .flatMap((path) => path.toolpath.moves)
            .filter((move) => move.kind === "cutterOn");
        expect(ons.length).toBe(2);
        // The pierce delay (G4 after the beam comes on) is the cutterOn's.
        expect(ons.every((move) => move.kind === "cutterOn" && move.pierceDelay === 0.5)).toBe(true);
    });

    test.each(posts.map((p) => p.id))("%s output is recognized as its dialect", (postId) => {
        const kind = postProcessor(postId)!.machineKinds[0] as "plasma" | "waterjet" | "laser";
        const { machine, paths, tool } = cuttingPaths(kind);
        expect(detectNcDialect(post(postId, camProgram(machine, paths, [tool])))).toBe(dialectOfPost(postId));
    });
});

// ------------------------------------------------------------------ Wire EDM

describe("round trip through the wire EDM post", () => {
    const wire = {
        wireDiameter: 0.25,
        sparkGap: 0.03,
        maxTaper: 15,
        programPlaneHeight: 0,
        uvPlaneHeight: 40,
    };

    test.each([
        ["vertical", {}],
        ["tapered", { taperAngle: 2 }],
        ["skims and a tab", { skims: 2, tabLength: 3 }],
    ])("%s", (_name, params) => {
        const tool: ToolData = {
            id: "wire",
            number: 1,
            name: "Wire",
            kind: "wire",
            diameter: 0.25,
            cutting: { feed: 5 },
        };
        const context = fakeContext({
            machine: { kind: "wireEdm", wire },
            tool,
            loops: [{ points: rectLoop(0, 0, 40, 20), closed: true, role: "sketch", z: 0 }],
            stock: { min: [-10, -10, 0], max: [50, 30, 30] },
        });
        const path = ok<ToolpathData>(
            wireContourOperation.generate(operation("wireContour", params), context),
        );
        const text = post("wire-iso", camProgram(context.machine, [path], [tool]));
        expect(detectNcDialect(text)).toBe("wire");
        const read = readBack(text, "wire-iso", context.machine);
        expectSameToolpaths([path], read, { xyOnly: true, ignoreFeed: true });
    });
});

// ------------------------------------------------------------------ Printers

describe("round trip through the printer posts", () => {
    const moves: ToolpathData["moves"] = [
        { kind: "comment", text: "LAYER_CHANGE" },
        { kind: "rapid", to: [10, 10, 0.2], feed: 9000 },
        { kind: "extrude", to: [30, 10, 0.2], extrude: 0.66, feed: 1500 },
        { kind: "extrude", to: [30, 30, 0.2], extrude: 0.66, feed: 1500 },
        { kind: "arc", to: [10, 30, 0.2], center: [20, 30, 0.2], clockwise: false, plane: "XY", feed: 1200 },
        { kind: "extrude", to: [10, 30, 0.2], extrude: -0.8, feed: 2100 },
        { kind: "rapid", to: [10, 30, 0.6], feed: 720 },
        { kind: "rapid", to: [50, 50, 0.6], feed: 9000 },
        { kind: "rapid", to: [50, 50, 0.4], feed: 720 },
        { kind: "extrude", to: [50, 50, 0.4], extrude: 0.8, feed: 2100 },
        { kind: "comment", text: "LAYER_CHANGE" },
        { kind: "extrude", to: [70, 50, 0.4], extrude: 0.5, feed: 1800 },
        { kind: "dwell", seconds: 2 },
        { kind: "rapid", to: [70, 50, 10], feed: 720 },
    ];

    test.each(postProcessors("printer").map((p) => p.id))("%s", (postId) => {
        const machine = machineProfile(
            postId === "prusa" ? "prusa-mk4s" : postId === "klipper" ? "voron-2-4-350" : "creality-ender-3",
        )!;
        expect(machine).not.toBeUndefined();
        const path: ToolpathData = { toolId: "nozzle-0.4", label: "Slice", moves };
        const text = post(postId, { ...camProgram(machine, [path], []), tools: new Map() });
        expect(detectNcDialect(text)).toBe(postId);
        const read = readBack(text, postId, machine);
        expectSameToolpaths([path], read, { printer: true });
        expect(read.stats.layers).toBe(2);
        expect(read.stats.filament).toBeCloseTo(0.66 + 0.66 - 0.8 + 0.8 + 0.5, 4);
    });
});
