// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import { Result } from "@chili3d/core";
import type { MachineProfileData } from "../model/machine";
import { type CamProgram, type PostProcessor, registerPostProcessor } from "../model/post";
import type { ToolpathMove, Vec3 } from "../model/toolpath";
import { estimatePrintTime, formatPrintDuration } from "./gcode/estimate";
import { parsePrinterGcode } from "./gcode/parse";
import { type PrinterPostOptions, printerConfigOf } from "./prusa/library";
import { readSlicerSettings } from "./prusa/settings";
import { firstNumber, formatNumber, unescapeString } from "./prusa/values";
import { printerKinematics } from "./slicer/slicer";
import { mayMove } from "./slicer/writer";

/**
 * Printer post-processors: Marlin, Prusa (Prusa-flavoured Marlin: printer/nozzle checks,
 * M73 progress and remaining time) and Klipper (layer info for the status display).
 *
 * Programs are written with absolute XYZ (G90) and relative extrusion (M83); travels and
 * extrusions are G1 with F written only when it changes; raw blocks (start/end G-code, a
 * whole PrusaSlicer program) pass through verbatim — after one that may move the head, every
 * axis and F is written again, and absolute positioning / relative extrusion are restored if
 * the block left them changed. A toolpath that is a complete program from another slicer is written unchanged.
 */

interface Dialect {
    readonly id: string;
    readonly name: string;
    readonly progressDefault: boolean;
    readonly prusa: boolean;
    readonly klipper: boolean;
}

const COMPLETE_PROGRAM = /^;\s*generated by (PrusaSlicer|SuperSlicer|OrcaSlicer|Slic3r|Cura|BambuStudio)/im;

/** A toolpath carrying another slicer's whole program (the PrusaSlicer bridge's output). */
export function isCompletePrinterProgram(moves: readonly ToolpathMove[]): boolean {
    const raws = moves.filter((move) => move.kind === "raw");
    return (
        raws.length > 0 &&
        moves.every((move) => move.kind === "raw" || move.kind === "comment") &&
        raws.some((move) => move.kind === "raw" && COMPLETE_PROGRAM.test(move.code))
    );
}

const xyz = (value: number) => formatNumber(value, 3);
const ePart = (value: number) => formatNumber(value, 5);

function commentLine(text: string): string {
    return /^[A-Z][A-Z_]*(:|$)/.test(text) ? `;${text}` : `; ${text}`;
}

/** Modes a raw block leaves behind (last G90/G91, M82/M83 outside comments). */
function modesAfter(code: string): { relativeXYZ?: boolean; absoluteE?: boolean } {
    let relativeXYZ: boolean | undefined;
    let absoluteE: boolean | undefined;
    for (const line of code.split("\n")) {
        const command = line.replace(/;.*$/, "").trim().toUpperCase();
        if (/^G90\b/.test(command)) relativeXYZ = false;
        else if (/^G91\b/.test(command)) relativeXYZ = true;
        else if (/^M82\b/.test(command)) absoluteE = true;
        else if (/^M83\b/.test(command)) absoluteE = false;
    }
    return { relativeXYZ, absoluteE };
}

function hasCommand(program: CamProgram, pattern: RegExp): boolean {
    return program.toolpaths.some((path) =>
        path.moves.some(
            (move) =>
                move.kind === "raw" &&
                move.code.split("\n").some((line) => pattern.test(line.replace(/;.*$/, "").trim())),
        ),
    );
}

function printerModel(machine: MachineProfileData): string {
    return unescapeString(printerConfigOf(machine)["printer_model"] ?? "").trim();
}

function writeProgram(program: CamProgram, options: PrinterPostOptions, dialect: Dialect): Result<string> {
    if (
        program.toolpaths.length > 0 &&
        program.toolpaths.every((path) => isCompletePrinterProgram(path.moves))
    ) {
        const code = program.toolpaths
            .flatMap((path) =>
                path.moves
                    .filter((move) => move.kind === "raw")
                    .map((move) => (move as { code: string }).code),
            )
            .join("\n");
        return Result.ok(code.endsWith("\n") ? code : `${code}\n`);
    }
    const machine = program.machine;
    const config = printerConfigOf(machine);
    const kinematics = printerKinematics(readSlicerSettings(config));
    const travelFeed =
        options.travelFeed ?? (machine.rapidFeed > 0 ? machine.rapidFeed : kinematics.rapidSpeed * 60);
    const all = program.toolpaths.flatMap((path) => path.moves);
    const estimate = estimatePrintTime(all, kinematics);
    const total = estimate.seconds;
    // Extrusion moves plus what raw blocks extrude (purge lines, retractions).
    const filament = all.reduce((sum, move) => {
        if (move.kind === "extrude") return sum + move.extrude;
        if (move.kind !== "raw") return sum;
        return (
            sum +
            parsePrinterGcode(move.code).moves.reduce((e, m) => e + (m.kind === "extrude" ? m.extrude : 0), 0)
        );
    }, 0);
    const layerCount = all.filter((move) => move.kind === "comment" && move.text === "LAYER_CHANGE").length;
    const progress = options.progress ?? dialect.progressDefault;
    const lines: string[] = [
        `; generated by Chili3d — ${dialect.name} post`,
        `; program: ${program.name}`,
        `; machine: ${machine.name}`,
        `; estimated printing time (normal mode) = ${formatPrintDuration(total)}`,
        `; filament used [mm] = ${filament.toFixed(2)}`,
    ];
    if (dialect.prusa) {
        const checks = options.printerChecks ?? "auto";
        const model = printerModel(machine);
        const nozzle = machine.printer?.nozzleDiameter ?? firstNumber(config["nozzle_diameter"], 0.4);
        if (checks === true || (checks === "auto" && !hasCommand(program, /^M862\.3\b/i) && model !== "")) {
            if (model !== "") lines.push(`M862.3 P "${model}" ; printer model check`);
        }
        if (checks === true || (checks === "auto" && !hasCommand(program, /^M862\.1\b/i))) {
            lines.push(`M862.1 P${formatNumber(nozzle)} ; nozzle diameter check`);
        }
    }
    const remaining = (elapsed: number) => Math.max(0, Math.round((total - elapsed) / 60));
    const percent = (elapsed: number) => (total > 0 ? Math.min(100, Math.floor((elapsed / total) * 100)) : 0);
    if (progress) lines.push(dialect.prusa || dialect.klipper ? `M73 P0 R${remaining(0)}` : "M73 P0");
    if (dialect.klipper && (options.layerInfo ?? true) && layerCount > 0) {
        lines.push(`SET_PRINT_STATS_INFO TOTAL_LAYER=${layerCount}`);
    }
    lines.push("G21 ; millimetres", "G90 ; absolute XYZ", "M83 ; relative extrusion");

    let x: number | undefined;
    let y: number | undefined;
    let z: number | undefined;
    let f: number | undefined;
    let layer = 0;
    let lastPercent = 0;
    let index = 0;
    const move = (to: Vec3, feed: number, e?: number, code = "G1") => {
        let line = code;
        if (to[0] !== x) line += ` X${xyz(to[0])}`;
        if (to[1] !== y) line += ` Y${xyz(to[1])}`;
        if (to[2] !== z) line += ` Z${xyz(to[2])}`;
        if (e !== undefined) line += ` E${ePart(e)}`;
        const rounded = Math.round(feed);
        if (rounded !== f && rounded > 0) {
            line += ` F${rounded}`;
            f = rounded;
        }
        x = to[0];
        y = to[1];
        z = to[2];
        if (line !== code) lines.push(line);
    };
    for (const path of program.toolpaths) {
        if (path.label) lines.push(`; ${path.label}`);
        for (const m of path.moves) {
            const elapsed = index > 0 ? estimate.elapsed[index - 1] : 0;
            index++;
            switch (m.kind) {
                case "comment":
                    if (m.text === "LAYER_CHANGE") {
                        if (progress && layer > 0) {
                            const p = percent(elapsed);
                            if (dialect.prusa || dialect.klipper)
                                lines.push(`M73 P${p} R${remaining(elapsed)}`);
                            else if (p !== lastPercent) lines.push(`M73 P${p}`);
                            lastPercent = p;
                        }
                        if (dialect.klipper && (options.layerInfo ?? true)) {
                            lines.push(
                                commentLine(m.text),
                                `SET_PRINT_STATS_INFO CURRENT_LAYER=${layer + 1}`,
                            );
                            layer++;
                            break;
                        }
                        layer++;
                    }
                    lines.push(commentLine(m.text));
                    break;
                case "raw": {
                    lines.push(m.code.replace(/\s+$/, ""));
                    if (mayMove(m.code)) x = y = z = f = undefined;
                    const modes = modesAfter(m.code);
                    if (modes.relativeXYZ) lines.push("G90 ; back to absolute XYZ");
                    if (modes.absoluteE) lines.push("M83 ; back to relative extrusion");
                    break;
                }
                case "rapid":
                    move(m.to, m.feed ?? travelFeed);
                    break;
                case "linear":
                    move(m.to, m.feed);
                    break;
                case "extrude":
                    move(m.to, m.feed, m.extrude);
                    break;
                case "arc": {
                    if (m.plane !== "XY")
                        return Result.err(`${dialect.name}: arcs outside the XY plane are not supported`);
                    const i = m.center[0] - (x ?? m.center[0]);
                    const j = m.center[1] - (y ?? m.center[1]);
                    const code = m.clockwise ? "G2" : "G3";
                    let line = `${code} X${xyz(m.to[0])} Y${xyz(m.to[1])}`;
                    if (m.to[2] !== z) line += ` Z${xyz(m.to[2])}`;
                    line += ` I${xyz(i)} J${xyz(j)}`;
                    if (Math.round(m.feed) !== f) {
                        f = Math.round(m.feed);
                        line += ` F${f}`;
                    }
                    lines.push(line);
                    x = m.to[0];
                    y = m.to[1];
                    z = m.to[2];
                    break;
                }
                case "dwell":
                    lines.push(`G4 P${Math.round(m.seconds * 1000)}`);
                    break;
                default:
                    return Result.err(`${dialect.name}: "${m.kind}" moves are not printer moves`);
            }
        }
    }
    if (progress) lines.push(dialect.prusa || dialect.klipper ? "M73 P100 R0" : "M73 P100");
    return Result.ok(`${lines.join("\n")}\n`);
}

function printerPost(dialect: Dialect): PostProcessor {
    return {
        id: dialect.id,
        name: dialect.name,
        machineKinds: ["printer"],
        extension: ".gcode",
        post(program, options) {
            const merged = {
                ...(program.machine.post.options ?? {}),
                ...(options ?? {}),
            } as PrinterPostOptions;
            return writeProgram(program, merged, dialect);
        },
    };
}

export const MARLIN_POST = printerPost({
    id: "marlin",
    name: "Marlin",
    progressDefault: false,
    prusa: false,
    klipper: false,
});
export const PRUSA_POST = printerPost({
    id: "prusa",
    name: "Prusa",
    progressDefault: true,
    prusa: true,
    klipper: false,
});
export const KLIPPER_POST = printerPost({
    id: "klipper",
    name: "Klipper",
    progressDefault: false,
    prusa: false,
    klipper: true,
});

export function registerPrinterPosts(): void {
    registerPostProcessor(MARLIN_POST);
    registerPostProcessor(PRUSA_POST);
    registerPostProcessor(KLIPPER_POST);
}
