// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import {
    type CamProgram,
    estimatePrintTime,
    formatPrintDuration,
    type MachineProfileData,
    machineProfile,
    moveEnd,
    parsePrinterGcode,
    postProcessor,
    postProcessors,
    printerGcodeStats,
    printerPreviewMoves,
    type ToolpathData,
    type ToolpathMove,
    toolpathPrintStats,
} from "../../src";
import { ok, printerContext } from "./context";
import { boxMesh } from "./meshes";

const program = (machine: MachineProfileData, ...toolpaths: ToolpathData[]): CamProgram => ({
    name: "job",
    machine,
    setup: printerContext(machine.id, boxMesh(0, 0, 0, 1, 1, 1)).setup,
    tools: new Map(),
    toolpaths,
});

const post = (
    id: string,
    machine: MachineProfileData,
    moves: ToolpathMove[],
    options?: Record<string, unknown>,
) => ok(postProcessor(id)!.post(program(machine, { toolId: "nozzle-0.4", label: "Slice", moves }), options));

/** Lines after the preamble's M83. */
const body = (gcode: string) => {
    const lines = gcode.trim().split("\n");
    return lines.slice(lines.indexOf("M83 ; relative extrusion") + 1);
};

const MOVES: ToolpathMove[] = [
    { kind: "raw", code: "G28 ; home" },
    { kind: "comment", text: "LAYER_CHANGE" },
    { kind: "raw", code: "G1 Z0.2 F720" },
    { kind: "rapid", to: [10, 10, 0.2], feed: 9000 },
    { kind: "comment", text: "TYPE:External perimeter" },
    { kind: "extrude", to: [20, 10, 0.2], extrude: 0.33264, feed: 1500 },
    { kind: "extrude", to: [20, 20, 0.2], extrude: 0.33264, feed: 1500 },
    { kind: "extrude", to: [20, 20, 0.2], extrude: -0.8, feed: 2100 },
    { kind: "rapid", to: [20, 20, 0.4], feed: 720 },
    { kind: "rapid", to: [50, 50, 0.4], feed: 9000 },
    { kind: "rapid", to: [50, 50, 0.2], feed: 720 },
    { kind: "extrude", to: [50, 50, 0.2], extrude: 0.8, feed: 2100 },
    { kind: "comment", text: "LAYER_CHANGE" },
    { kind: "rapid", to: [50, 50, 0.4], feed: 720 },
    { kind: "extrude", to: [60, 50, 0.4], extrude: 0.33264, feed: 1500 },
    { kind: "comment", text: "a note" },
];

describe("printer posts", () => {
    const ender = machineProfile("creality-ender-3")!;
    const mk4s = machineProfile("prusa-mk4s")!;
    const voron = machineProfile("voron-2-4-350")!;

    test("the three printer posts are registered for printers only", () => {
        const ids = postProcessors("printer").map((p) => p.id);
        expect(ids).toEqual(expect.arrayContaining(["klipper", "marlin", "prusa"]));
        expect(postProcessors("mill").some((p) => p.id === "prusa")).toBe(false);
        expect(postProcessor("marlin")?.extension).toBe(".gcode");
    });

    test("Marlin: absolute XYZ, relative E, F only when it changes, raw blocks verbatim", () => {
        const gcode = post("marlin", ender, MOVES);
        const lines = gcode.trim().split("\n");
        expect(lines[0]).toBe("; generated by Chili3d — Marlin post");
        expect(lines).toContain("G21 ; millimetres");
        expect(lines).toContain("G90 ; absolute XYZ");
        expect(gcode).not.toContain("M73");
        expect(body(gcode)).toEqual([
            "; Slice",
            "G28 ; home",
            ";LAYER_CHANGE",
            "G1 Z0.2 F720",
            // After raw code every axis is written again.
            "G1 X10 Y10 Z0.2 F9000",
            ";TYPE:External perimeter",
            "G1 X20 E0.33264 F1500",
            "G1 Y20 E0.33264",
            "G1 E-0.8 F2100",
            "G1 Z0.4 F720",
            "G1 X50 Y50 F9000",
            "G1 Z0.2 F720",
            "G1 E0.8 F2100",
            ";LAYER_CHANGE",
            "G1 Z0.4 F720",
            "G1 X60 E0.33264 F1500",
            "; a note",
        ]);
    });

    test("raw code that switches modes is followed by absolute XYZ and relative E again", () => {
        const gcode = post("marlin", ender, [
            { kind: "raw", code: "M82 ; absolute E\nG91\nG1 Z5\nG92 E0" },
            { kind: "rapid", to: [1, 2, 3] },
        ]);
        expect(body(gcode)).toEqual([
            "; Slice",
            "M82 ; absolute E",
            "G91",
            "G1 Z5",
            "G92 E0",
            "G90 ; back to absolute XYZ",
            "M83 ; back to relative extrusion",
            // A travel without a feed runs at the machine's rapid feed.
            `G1 X1 Y2 Z3 F${ender.rapidFeed}`,
        ]);
    });

    test("Prusa: printer checks when the program has none, M73 progress per layer", () => {
        const gcode = post("prusa", mk4s, MOVES);
        const lines = gcode.trim().split("\n");
        expect(lines).toContain('M862.3 P "MK4S" ; printer model check');
        expect(lines).toContain("M862.1 P0.4 ; nozzle diameter check");
        const progress = lines.filter((line) => line.startsWith("M73"));
        expect(progress[0]).toMatch(/^M73 P0 R\d+$/);
        expect(progress).toHaveLength(3);
        expect(progress[1]).toMatch(/^M73 P\d+ R\d+$/);
        expect(progress[2]).toBe("M73 P100 R0");
        // M73 comes before its layer's marker.
        expect(lines[lines.indexOf(progress[1]) + 1]).toBe(";LAYER_CHANGE");
        const withChecks = post("prusa", mk4s, [
            { kind: "raw", code: 'M862.3 P "MK4S"\nM862.1 P0.4' },
            ...MOVES,
        ]);
        expect(withChecks.split("\n").filter((line) => line.startsWith("M862"))).toHaveLength(2);
        const noProgress = post("prusa", mk4s, MOVES, { progress: false, printerChecks: false });
        expect(noProgress).not.toContain("M73");
        expect(noProgress).not.toContain("M862");
    });

    test("Klipper: print stats layer info", () => {
        const lines = post("klipper", voron, MOVES).trim().split("\n");
        expect(lines).toContain("SET_PRINT_STATS_INFO TOTAL_LAYER=2");
        expect(lines.filter((line) => line.startsWith("SET_PRINT_STATS_INFO CURRENT_LAYER"))).toEqual([
            "SET_PRINT_STATS_INFO CURRENT_LAYER=1",
            "SET_PRINT_STATS_INFO CURRENT_LAYER=2",
        ]);
        expect(lines.some((line) => line.startsWith("M73"))).toBe(false);
    });

    test("a complete program from another slicer is written unchanged", () => {
        const sliced =
            "; generated by PrusaSlicer 2.8.1+linux\nG28\nG1 X1 Y1 E1\n; filament used [mm] = 1.00\n";
        expect(post("prusa", mk4s, [{ kind: "raw", code: sliced }])).toBe(sliced);
        expect(post("marlin", ender, [{ kind: "raw", code: sliced.trimEnd() }])).toBe(sliced);
    });

    test("mill moves are refused", () => {
        const result = postProcessor("marlin")!.post(
            program(ender, {
                toolId: "t",
                moves: [{ kind: "drill", at: [0, 0, 0], depth: 1, retract: 1, cycle: "drill", feed: 100 }],
            }),
        );
        expect(result.isOk).toBe(false);
        expect(result.error).toContain('"drill"');
    });
});

describe("printer G-code reading and estimates", () => {
    test("absolute and relative extrusion, G91 and G92 come out as relative amounts", () => {
        const parsed = parsePrinterGcode(
            [
                "G90",
                "M82",
                "G92 E0",
                "G1 X10 Y0 Z0.2 E1.5 F1200 ; absolute E",
                "G1 X20 E2.5",
                "G1 E1.7 F2100 ; retract",
                "M83",
                "G1 E0.8",
                "G91",
                "G1 X5 E0.4",
                "G90",
                "G0 X0 Y0",
            ].join("\n"),
        );
        expect(parsed.moves).toEqual([
            { kind: "extrude", to: [10, 0, 0.2], extrude: 1.5, feed: 1200 },
            { kind: "extrude", to: [20, 0, 0.2], extrude: 1, feed: 1200 },
            { kind: "extrude", to: [20, 0, 0.2], extrude: expect.closeTo(-0.8, 9), feed: 2100 },
            { kind: "extrude", to: [20, 0, 0.2], extrude: 0.8, feed: 2100 },
            { kind: "extrude", to: [25, 0, 0.2], extrude: 0.4, feed: 2100 },
            { kind: "rapid", to: [0, 0, 0.2], feed: 2100 },
        ]);
        // The first extrusion starts at the origin.
        expect(parsed.extrusionBounds).toEqual({ min: [0, 0, 0], max: [25, 0, 0.2] });
    });

    test("arcs flatten into segments that share the arc's extrusion", () => {
        const parsed = parsePrinterGcode("G1 X10 Y0 F600\nG3 X-10 Y0 I-10 J0 E3.2");
        const arc = parsed.moves.slice(1);
        expect(arc.length).toBe(36);
        expect(arc.reduce((sum, m) => sum + (m.kind === "extrude" ? m.extrude : 0), 0)).toBeCloseTo(3.2, 9);
        for (const m of arc) expect(Math.hypot(moveEnd(m)![0], moveEnd(m)![1])).toBeCloseTo(10, 9);
        expect(moveEnd(arc[17])![1]).toBeGreaterThan(9.9);
    });

    test("slicer statistics comments are read", () => {
        const stats = printerGcodeStats(
            [
                ";LAYER_CHANGE",
                ";LAYER_CHANGE",
                "; filament used [mm] = 1234.56",
                "; filament used [g] = 3.70",
                "; estimated printing time (normal mode) = 1h 2m 3s",
                "; estimated printing time (silent mode) = 2h 0m 0s",
            ].join("\n"),
        );
        expect(stats).toEqual({ seconds: 3723, filamentMm: 1234.56, filamentGrams: 3.7, layers: 2 });
        expect(formatPrintDuration(3723)).toBe("1h 2m 3s");
        expect(formatPrintDuration(59)).toBe("59s");
    });

    test("a toolpath's raw G-code previews as moves", () => {
        const toolpath: ToolpathData = {
            toolId: "n",
            moves: [
                { kind: "raw", code: "G1 X5 Y5 Z0.2 F3000\nG1 X15 E0.5" },
                { kind: "extrude", to: [15, 15, 0.2], extrude: 0.5, feed: 1200 },
            ],
        };
        const preview = printerPreviewMoves(toolpath);
        expect(preview).toEqual([
            { kind: "rapid", to: [5, 5, 0.2], feed: 3000 },
            { kind: "extrude", to: [15, 5, 0.2], extrude: 0.5, feed: 3000 },
            { kind: "extrude", to: [15, 15, 0.2], extrude: 0.5, feed: 1200 },
        ]);
        expect(printerPreviewMoves(toolpath)).toBe(preview);
    });

    test("time estimates follow trapezoidal speed profiles", () => {
        const kinematics = { acceleration: 1000, travelAcceleration: 1000, jerk: 8, rapidSpeed: 100 };
        // 100 mm at 50 mm/s from rest to rest: 2 s cruising plus 50/1000 s lost to ramps.
        const straight = estimatePrintTime(
            [
                { kind: "rapid", to: [0, 0, 0] },
                { kind: "extrude", to: [100, 0, 0], extrude: 3, feed: 3000 },
            ],
            kinematics,
        );
        expect(straight.seconds).toBeCloseTo(2.05, 9);
        // A short move cannot reach its feed: a triangle profile, 2·sqrt(L/a).
        const short = estimatePrintTime(
            [
                { kind: "rapid", to: [0, 0, 0] },
                { kind: "extrude", to: [1, 0, 0], extrude: 0.03, feed: 6000 },
            ],
            kinematics,
        );
        expect(short.seconds).toBeCloseTo(2 * Math.sqrt(1 / 1000), 9);
        // Collinear moves keep their speed through the junction.
        const split = estimatePrintTime(
            [
                { kind: "rapid", to: [0, 0, 0] },
                { kind: "extrude", to: [50, 0, 0], extrude: 1.5, feed: 3000 },
                { kind: "extrude", to: [100, 0, 0], extrude: 1.5, feed: 3000 },
            ],
            kinematics,
        );
        expect(split.seconds).toBeCloseTo(2.05, 9);
        expect(split.elapsed[2]).toBeCloseTo(2.05, 9);
        // A retraction takes |E| / feed.
        const retract = estimatePrintTime([
            { kind: "rapid", to: [0, 0, 0] },
            { kind: "extrude", to: [0, 0, 0], extrude: -0.8, feed: 2400 },
        ]);
        expect(retract.seconds).toBeCloseTo(0.02, 9);
    });

    test("print stats of either slicer's toolpath", () => {
        const machine = machineProfile("creality-ender-3")!;
        const sliced = toolpathPrintStats(
            {
                toolId: "n",
                moves: [
                    {
                        kind: "raw",
                        code: "; generated by PrusaSlicer\n; filament used [mm] = 5.5\n; total layers count = 3\n; estimated printing time (normal mode) = 10m 0s",
                    },
                ],
            },
            machine,
        );
        expect(sliced).toEqual({ seconds: 600, filamentMm: 5.5, layers: 3 });
        const own = toolpathPrintStats({ toolId: "n", moves: MOVES }, machine);
        expect(own.layers).toBe(2);
        expect(own.filamentMm).toBeCloseTo(3 * 0.33264, 9);
        expect(own.seconds).toBeGreaterThan(0);
    });
});
