// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import http from "node:http";
import type { AddressInfo } from "node:net";
import os from "node:os";
import path from "node:path";
import JSZip from "jszip";
import { createBridgeServer } from "../../../../scripts/prusa-slicer-bridge.mjs";
import {
    camOperation,
    isCompletePrinterProgram,
    machineProfile,
    postProcessor,
    printerPreviewMoves,
    sliceWithBridge,
} from "../../src";
import { ok, printerContext } from "./context";
import { boxMesh } from "./meshes";

/**
 * A stand-in for the prusa-slicer CLI: answers --help with a version line; for
 * --export-gcode writes a G-code that echoes its arguments, the INI it was given and the
 * model it read; fails when the INI asks it to.
 */
const FAKE_SLICER = String.raw`
import { readFileSync, writeFileSync } from "node:fs";
const args = process.argv.slice(2);
if (args.includes("--help")) {
    console.log("PrusaSlicer-2.8.1+fake based on Slic3r (with GUI)");
    process.exit(0);
}
const value = (flag) => args[args.indexOf(flag) + 1];
const ini = readFileSync(value("--load"), "utf8");
if (/^fail_on_purpose = 1$/m.test(ini)) {
    console.error("error: the configuration is invalid on purpose");
    process.exit(2);
}
const modelPath = args[args.length - 1];
const model = readFileSync(modelPath);
const lines = [
    "; generated by PrusaSlicer 2.8.1+fake on 2026-10-07 at 12:00:00 UTC",
    "; args: " + JSON.stringify(args),
    "; model: " + modelPath,
    "; model bytes: " + model.length + " magic " + model.subarray(0, 2).toString("latin1"),
    ...ini.split("\n").map((line) => "; ini: " + line),
    "G90",
    "M83",
    ";LAYER_CHANGE",
    "G1 Z0.2 F720",
    "G1 X100 Y100 F9000",
    "G1 X110 Y100 E0.33 F1800",
    "G1 X110 Y110 E0.33",
    "; filament used [mm] = 0.66",
    "; estimated printing time (normal mode) = 1m 5s",
];
writeFileSync(value("--output"), lines.join("\n") + "\n");
console.log("Slicing done");
`;

interface Reply {
    readonly status: number;
    readonly headers: http.IncomingHttpHeaders;
    readonly body: string;
}

function request(
    url: string,
    init: { method?: string; headers?: Record<string, string>; body?: string } = {},
): Promise<Reply> {
    return new Promise((resolve, reject) => {
        const req = http.request(url, { method: init.method ?? "GET", headers: init.headers }, (res) => {
            const chunks: Buffer[] = [];
            res.on("data", (chunk) => chunks.push(chunk));
            res.on("end", () =>
                resolve({
                    status: res.statusCode ?? 0,
                    headers: res.headers,
                    body: Buffer.concat(chunks).toString("utf8"),
                }),
            );
        });
        req.on("error", reject);
        if (init.body !== undefined) req.write(init.body);
        req.end();
    });
}

/** A fetch over node:http (the app's code path, without the DOM fetch's origin rules). */
async function nodeFetch(
    url: string,
    init: { method?: string; headers?: Record<string, string>; body?: string } = {},
) {
    const reply = await request(url, init);
    return {
        ok: reply.status >= 200 && reply.status < 300,
        status: reply.status,
        json: async () => JSON.parse(reply.body),
    } as unknown as Response;
}

describe("PrusaSlicer bridge", () => {
    let dir: string;
    let server: http.Server;
    let base: string;

    beforeAll(async () => {
        dir = mkdtempSync(path.join(os.tmpdir(), "chili3d-fake-slicer-"));
        const fake = path.join(dir, "prusa-slicer.mjs");
        writeFileSync(fake, FAKE_SLICER);
        server = createBridgeServer({
            slicer: { command: process.execPath, args: [fake] },
            origins: ["https://cad.example"],
            log: () => {},
        });
        await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", () => resolve()));
        base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
    });

    afterAll(async () => {
        await new Promise<void>((resolve) => server.close(() => resolve()));
        rmSync(dir, { recursive: true, force: true });
    });

    const slice = (body: unknown, headers: Record<string, string> = {}) =>
        request(`${base}/slice`, {
            method: "POST",
            headers: { "Content-Type": "application/json", ...headers },
            body: typeof body === "string" ? body : JSON.stringify(body),
        });

    test("health reports the slicer's version line", async () => {
        const reply = await request(`${base}/health`);
        expect(reply.status).toBe(200);
        expect(JSON.parse(reply.body)).toMatchObject({
            ok: true,
            version: "PrusaSlicer-2.8.1+fake based on Slic3r (with GUI)",
        });
    });

    test("a slice runs prusa-slicer on the model and INI and returns its G-code", async () => {
        const model = Buffer.from("PK fake 3mf bytes");
        const reply = await slice({
            model: model.toString("base64"),
            modelName: "job.3mf",
            config: "layer_height = 0.2\nbinary_gcode = 1",
        });
        expect(reply.status).toBe(200);
        const result = JSON.parse(reply.body) as { ok: boolean; gcode: string; log: string };
        expect(result.ok).toBe(true);
        expect(result.log).toContain("Slicing done");
        const lines = result.gcode.split("\n");
        const args = JSON.parse(lines[1].slice("; args: ".length)) as string[];
        expect(args.slice(0, 3)).toEqual(["--export-gcode", "--dont-arrange", "--load"]);
        expect(args[3]).toMatch(/job\.ini$/);
        expect(args[4]).toBe("--output");
        expect(args[5]).toMatch(/job\.gcode$/);
        expect(args[6]).toMatch(/job\.3mf$/);
        expect(lines[3]).toBe(`; model bytes: ${model.length} magic PK`);
        // The job's own binary_gcode is replaced: PrusaSlicer refuses repeated keys.
        const ini = lines.filter((line) => line.startsWith("; ini: ")).map((line) => line.slice(7));
        expect(ini.filter((line) => line.startsWith("binary_gcode"))).toEqual(["binary_gcode = 0"]);
        expect(ini).toContain("layer_height = 0.2");
        // The job's temporary directory is gone.
        expect(existsSync(lines[2].slice("; model: ".length))).toBe(false);
    });

    test("arrange lets PrusaSlicer place the objects; STL models keep their type", async () => {
        const reply = await slice({
            model: Buffer.from("solid x").toString("base64"),
            modelName: "part.stl",
            config: "",
            arrange: true,
        });
        const gcode = (JSON.parse(reply.body) as { gcode: string }).gcode;
        const args = JSON.parse(gcode.split("\n")[1].slice(8)) as string[];
        expect(args).not.toContain("--dont-arrange");
        expect(args[args.length - 1]).toMatch(/job\.stl$/);
    });

    test("bad requests and slicer failures are reported", async () => {
        expect((await slice("{not json")).status).toBe(400);
        expect((await slice({ config: "" })).status).toBe(400);
        expect((await slice({ model: "", config: "" })).status).toBe(400);
        const unsupported = await slice({ model: "AAAA", modelName: "part.exe", config: "" });
        expect(unsupported.status).toBe(422);
        expect(JSON.parse(unsupported.body).error).toContain('".exe"');
        const failed = await slice({
            model: Buffer.from("PK").toString("base64"),
            config: "fail_on_purpose = 1",
        });
        expect(failed.status).toBe(422);
        const body = JSON.parse(failed.body) as { ok: boolean; error: string; log: string };
        expect(body.ok).toBe(false);
        expect(body.error).toBe("prusa-slicer exited with code 2");
        expect(body.log).toContain("invalid on purpose");
        expect((await request(`${base}/nothing`)).status).toBe(404);
    });

    test("CORS: allowed origins get headers and preflights, others are refused", async () => {
        const preflight = await request(`${base}/slice`, {
            method: "OPTIONS",
            headers: {
                Origin: "https://cad.example",
                "Access-Control-Request-Method": "POST",
                "Access-Control-Request-Private-Network": "true",
            },
        });
        expect(preflight.status).toBe(204);
        expect(preflight.headers["access-control-allow-origin"]).toBe("https://cad.example");
        expect(preflight.headers["access-control-allow-methods"]).toContain("POST");
        expect(preflight.headers["access-control-allow-headers"]).toBe("Content-Type");
        expect(preflight.headers["access-control-allow-private-network"]).toBe("true");
        const dev = await request(`${base}/health`, { headers: { Origin: "http://localhost:8080" } });
        expect(dev.headers["access-control-allow-origin"]).toBe("http://localhost:8080");
        const other = await request(`${base}/health`, { headers: { Origin: "https://evil.example" } });
        expect(other.status).toBe(403);
        expect(other.headers["access-control-allow-origin"]).toBeUndefined();
    });

    test("the PrusaSlicer operation sends the job's 3MF and INI and returns the G-code as a raw toolpath", async () => {
        const calls: {
            url: string;
            body: { model: string; modelName: string; config: string; arrange: boolean };
        }[] = [];
        rs.stubGlobal(
            "fetch",
            async (
                url: string,
                init: { method?: string; headers?: Record<string, string>; body?: string },
            ) => {
                calls.push({ url, body: JSON.parse(init.body ?? "{}") });
                return nodeFetch(url, init);
            },
        );
        try {
            const handler = camOperation("prusaSlicer")!;
            expect(handler.label).toBe("PrusaSlicer (local)");
            const machine = machineProfile("prusa-mk4s")!;
            const params = { ...handler.defaults(machine), bridgeUrl: `${base}/`, perimeters: 5 };
            expect(handler.defaults(machine)).toMatchObject({
                printPreset: "0.20mm SPEED",
                bridgeUrl: "http://127.0.0.1:7781",
                arrange: false,
            });
            const context = printerContext("prusa-mk4s", boxMesh(100, 90, 0, 120, 110, 10));
            const toolpath = ok(
                await handler.generate(
                    { id: "op", type: "prusaSlicer", name: "PrusaSlicer job", params },
                    context,
                ),
            );
            expect(calls).toHaveLength(1);
            expect(calls[0].url).toBe(`${base}/slice`);
            expect(calls[0].body.modelName).toBe("job.3mf");
            expect(calls[0].body.arrange).toBe(false);
            const zip = await JSZip.loadAsync(Buffer.from(calls[0].body.model, "base64"));
            expect(Object.keys(zip.files)).toContain("Metadata/Slic3r_PE.config");
            expect(await zip.file("Metadata/Slic3r_PE.config")!.async("string")).toContain(
                "; perimeters = 5",
            );
            expect(calls[0].body.config).toContain("\nperimeters = 5\n");
            expect(calls[0].body.config).toContain("printer_settings_id = Original Prusa MK4S 0.4 nozzle");

            expect(toolpath.label).toBe("PrusaSlicer job");
            expect(toolpath.moves).toHaveLength(1);
            expect(toolpath.moves[0].kind).toBe("raw");
            expect(isCompletePrinterProgram(toolpath.moves)).toBe(true);
            const code = (toolpath.moves[0] as { code: string }).code;
            // The printer post writes PrusaSlicer's program unchanged.
            const posted = ok(
                postProcessor("prusa")!.post({
                    name: "job",
                    machine,
                    setup: context.setup,
                    tools: new Map(),
                    toolpaths: [toolpath],
                }),
            );
            expect(posted).toBe(code);
            // And the preview sees its motions.
            const preview = printerPreviewMoves(toolpath).filter((m) => m.kind === "extrude");
            expect(preview).toEqual([
                { kind: "extrude", to: [110, 100, 0.2], extrude: 0.33, feed: 1800 },
                { kind: "extrude", to: [110, 110, 0.2], extrude: 0.33, feed: 1800 },
            ]);
        } finally {
            rs.unstubAllGlobals();
        }
    });

    test("an unreachable bridge is an error result, not a throw", async () => {
        rs.stubGlobal("fetch", async () => {
            throw new TypeError("fetch failed");
        });
        try {
            const result = await sliceWithBridge("http://127.0.0.1:9", {
                model: new Uint8Array([1]),
                modelName: "a.3mf",
                config: "",
            });
            expect(result.isOk).toBe(false);
            expect(result.error).toContain("not reachable");
            expect(result.error).toContain("prusa-slicer-bridge.mjs");
        } finally {
            rs.unstubAllGlobals();
        }
    });
});
