// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import {
    evaluatePrusaCondition,
    expandPrusaMacros,
    importPrusaConfig,
    isPresetCompatible,
    machineFromPrinterPreset,
    machineProfile,
    machineProfiles,
    parsePrusaBundle,
    parsePrusaConfigText,
    parsePrusaIni,
    printerConfigOf,
    prusaMacroScope,
    prusaPreset,
    prusaPresets,
    resolvePrusaJob,
} from "../../src";
import { escapeString, floatOrPercent, parseStrings, unescapeString } from "../../src/additive/prusa/values";
import { ok } from "./context";

const BUNDLE = String.raw`
# a vendor-style bundle
[vendor]
name = Test Vendor
config_version = 0.1.0

[printer_model:T1]
name = Test One
variants = 0.4

[print:*common*]
layer_height = 0.2
perimeters = 2
fill_density = 15%
start_note = a = b ; not a comment

[print:*fine*]
layer_height = 0.1
top_solid_layers = 7

[print:*strong*]
perimeters = 4

[print:Fine strong]
inherits = *common*; *fine*; *strong*
fill_density = 30%

[print:Orphan]
inherits = *missing*
perimeters = 3

[print:Loop A]
inherits = Loop B

[print:Loop B]
inherits = Loop A

[filament:*pla*]
filament_type = PLA
temperature = 210

[filament:Brand PLA]
inherits = *pla*
temperature = 205
compatible_printers = "Test One 0.4"

[printer:*base*]
gcode_flavor = marlin2
bed_shape = 0x0,200x0,200x200,0x200
max_print_height = 180
nozzle_diameter = 0.4
start_gcode = G28\nG1 Z5 F3000

[printer:Test One 0.4]
inherits = *base*
printer_model = T1
printer_notes = PRINTER_VENDOR_TEST
`;

describe("PrusaSlicer INI files", () => {
    test("sections, comments and values containing = and ;", () => {
        const file = parsePrusaIni(BUNDLE);
        expect(file.sections.map((s) => `${s.type}:${s.name}`).slice(0, 3)).toEqual([
            "vendor:",
            "printer_model:T1",
            "print:*common*",
        ]);
        expect(file.sections[2].values["start_note"]).toBe("a = b ; not a comment");
        expect(file.sections[0].values["name"]).toBe("Test Vendor");
    });

    test("bundle presets resolve their inherits chains left to right, then their own keys", () => {
        const value = ok(parsePrusaBundle(BUNDLE));
        const fine = value.prints.get("Fine strong");
        expect(fine?.config).toEqual({
            layer_height: "0.1",
            perimeters: "4",
            fill_density: "30%",
            start_note: "a = b ; not a comment",
            top_solid_layers: "7",
        });
        expect(fine?.abstract).toBe(false);
        expect(value.prints.get("*common*")?.abstract).toBe(true);
        expect(value.filaments.get("Brand PLA")?.config["temperature"]).toBe("205");
        expect(value.filaments.get("Brand PLA")?.config["filament_type"]).toBe("PLA");
        expect(value.printers.get("Test One 0.4")?.config["max_print_height"]).toBe("180");
        expect(value.printerModels.get("T1")?.["name"]).toBe("Test One");
        expect(value.vendor?.["name"]).toBe("Test Vendor");
    });

    test("missing parents and inheritance cycles are reported, the presets still resolve", () => {
        const value = ok(parsePrusaBundle(BUNDLE));
        expect(value.prints.get("Orphan")?.config).toEqual({ perimeters: "3" });
        expect(value.warnings.some((w) => w.includes('missing "*missing*"'))).toBe(true);
        expect(value.warnings.some((w) => w.includes("cycle"))).toBe(true);
        expect(value.prints.get("Loop A")?.config).toEqual({});
    });

    test("a text without preset sections is not a bundle", () => {
        expect(parsePrusaBundle("layer_height = 0.2").isOk).toBe(false);
    });

    test("a single exported config splits into print, filament and printer presets", () => {
        const exported = [
            "# generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2024-08-01 at 10:00:00 UTC",
            "bed_shape = 0x0,250x0,250x210,0x210",
            "bed_temperature = 60",
            "fill_density = 20%",
            'filament_settings_id = "My PLA"',
            "layer_height = 0.15",
            "machine_max_feedrate_x = 200",
            "print_settings_id = My print",
            "printer_settings_id = My printer",
            "start_gcode = G28\\nG29",
            "temperature = 215",
        ].join("\n");
        const bundle = ok(parsePrusaConfigText(exported));
        const print = bundle.prints.get("My print");
        const filament = bundle.filaments.get("My PLA");
        const printer = bundle.printers.get("My printer");
        expect(print?.config).toEqual({ fill_density: "20%", layer_height: "0.15" });
        expect(filament?.config).toEqual({ bed_temperature: "60", temperature: "215" });
        expect(printer?.config).toEqual({
            bed_shape: "0x0,250x0,250x210,0x210",
            machine_max_feedrate_x: "200",
            start_gcode: "G28\\nG29",
        });
    });

    test("the commented form of a 3MF config or G-code footer reads like an INI", () => {
        const footer = [
            "; generated by PrusaSlicer 2.8.1",
            "",
            "; estimated printing time (normal mode) = 1h 2m",
            "; layer_height = 0.25",
            "; print_settings_id = Footer print",
            "; printer_settings_id = Footer printer",
            "; nozzle_diameter = 0.6",
        ].join("\n");
        const bundle = ok(parsePrusaConfigText(footer));
        expect(bundle.prints.get("Footer print")?.config).toEqual({ layer_height: "0.25" });
        expect(bundle.printers.get("Footer printer")?.config).toEqual({ nozzle_diameter: "0.6" });
    });
});

describe("PrusaSlicer values", () => {
    test("strings unescape and escape C-style", () => {
        expect(unescapeString("G28\\nG1 Z5\\\\")).toBe("G28\nG1 Z5\\");
        expect(unescapeString('"quoted"')).toBe("quoted");
        expect(escapeString("G28\nG1 Z5\\")).toBe("G28\\nG1 Z5\\\\");
    });

    test("string vectors split on ; and honour quotes", () => {
        expect(parseStrings('"Generic PLA";"My \\"best\\" PETG"')).toEqual(["Generic PLA", 'My "best" PETG']);
        expect(parseStrings("a;b")).toEqual(["a", "b"]);
    });

    test.each([
        ["0.45", 0.4, 0.45],
        ["112.5%", 0.4, 0.45],
        ["0", 0.4, 0.5],
        [undefined, 0.4, 0.5],
    ])("float-or-percent %s over %d (auto 0.5)", (text, base, expected) => {
        expect(floatOrPercent(text, base, 0.5)).toBeCloseTo(expected, 9);
    });
});

describe("custom G-code macros", () => {
    const scope = prusaMacroScope(
        {
            first_layer_temperature: "215,220",
            nozzle_diameter: "0.4",
            printer_notes: "PRINTER_VENDOR_PRUSA3D\\nPRINTER_MODEL_MK4",
            printer_model: "MK4S",
            max_print_height: "220",
            filament_type: "PETG",
        },
        { layer_num: 3, layer_z: 0.8, first_layer_print_min: [10.5, 20] },
    );

    test("legacy placeholders, indexed and not, and unknown names left as text", () => {
        const result = expandPrusaMacros(
            "M104 S[first_layer_temperature] T[first_layer_temperature_1] ; [not_a_var]",
            scope,
        );
        expect(result.text).toBe("M104 S215 T220 ; [not_a_var]");
        expect(result.errors).toEqual([]);
    });

    test("expressions, functions, ternaries and locals", () => {
        const text = expandPrusaMacros(
            "{first_layer_temperature[0] - 10} {max(layer_z + 10, max_print_height)} {min(1, 2)} " +
                '{layer_num > 2 ? "high" : "low"} {local z = layer_z * 2; z} {first_layer_print_min[0]} ' +
                '{digits(layer_z, 0, 2)} {is_nil(first_layer_temperature[0])} {one_of(filament_type, "PLA", "PETG")}',
            scope,
        );
        expect(text.errors).toEqual([]);
        expect(text.text).toBe("205 220 1 high 1.6 10.5 0.80 false true");
    });

    test("if / elsif / else blocks, nested, with regex matches", () => {
        const template =
            "{if printer_notes=~/.*PRINTER_MODEL_MK4.*/}MK4{if layer_num == 3} at three{endif}" +
            "{elsif nozzle_diameter[0] == 0.6}big{else}other{endif};";
        expect(expandPrusaMacros(template, scope).text).toBe("MK4 at three;");
        expect(expandPrusaMacros("{if filament_type !~ /PLA/}not PLA{else}PLA{endif}", scope).text).toBe(
            "not PLA",
        );
        expect(expandPrusaMacros("{if not (layer_num < 2) and layer_z > 0.5}yes{endif}", scope).text).toBe(
            "yes",
        );
    });

    test("errors are reported and print nothing", () => {
        const result = expandPrusaMacros("G1 Z{unknown_option + 1} F720", scope);
        expect(result.text).toBe("G1 Z F720");
        expect(result.errors[0]).toContain("unknown variable");
        expect(expandPrusaMacros("{if layer_num}open", scope).errors[0]).toContain("{endif}");
    });

    test("compatibility conditions evaluate against a printer config", () => {
        expect(
            evaluatePrusaCondition(
                'printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_model=="MK4S"',
                scope,
            ).value,
        ).toBe(true);
        expect(evaluatePrusaCondition("nozzle_diameter[0]==0.6", scope).value).toBe(false);
        expect(evaluatePrusaCondition("", scope).value).toBe(true);
    });
});

describe("built-in printer profiles", () => {
    test.each([
        ["prusa-mk4s", "Original Prusa MK4S 0.4 nozzle", 250, 210, 220, "prusa", "prusa"],
        ["prusa-mk4", "Original Prusa MK4 Input Shaper 0.4 nozzle", 250, 210, 220, "prusa", "prusa"],
        ["prusa-mk3s", "Original Prusa i3 MK3S & MK3S+", 250, 210, 210, "prusa", "prusa"],
        ["prusa-mini", "Original Prusa MINI & MINI+", 180, 180, 180, "prusa", "prusa"],
        ["prusa-xl", "Original Prusa XL 0.4 nozzle", 360, 360, 360, "prusa", "prusa"],
        ["prusa-core-one", "Prusa CORE One 0.4 nozzle", 250, 220, 270, "prusa", "prusa"],
        ["creality-ender-3", "Creality Ender-3", 220, 220, 250, "marlin", "marlin"],
        ["voron-2-4-350", "Voron 2.4 350", 350, 350, 340, "klipper", "klipper"],
    ])("%s is a registered printer machine", (id, name, x, y, height, flavor, post) => {
        const machine = machineProfile(id);
        expect(machine?.name).toBe(name);
        expect(machine?.kind).toBe("printer");
        expect(machine?.printer?.bed).toEqual({ x, y, shape: "rectangle" });
        expect(machine?.printer?.maxHeight).toBe(height);
        expect(machine?.printer?.nozzleDiameter).toBe(0.4);
        expect(machine?.printer?.filamentDiameter).toBe(1.75);
        expect(machine?.printer?.flavor).toBe(flavor);
        expect(machine?.printer?.prusaSlicerPreset).toBe(name);
        expect(machine?.post.id).toBe(post);
        expect(machine?.linearAxes.find((axis) => axis.name === "Z")?.max).toBe(height);
        expect(machine?.tools?.[0]).toMatchObject({ kind: "nozzle", diameter: 0.4 });
        expect(printerConfigOf(machine!)["start_gcode"]).not.toBe("");
    });

    test("printers list by kind and only printers carry printer data", () => {
        const printers = machineProfiles("printer").map((machine) => machine.id);
        expect(printers).toEqual(expect.arrayContaining(["prusa-mk4s", "creality-ender-3", "voron-2-4-350"]));
        expect(machineProfiles("mill").some((machine) => machine.id === "prusa-mk4s")).toBe(false);
    });

    test("print presets follow the printer's speed family; abstract presets stay hidden", () => {
        const fast = prusaPresets("print", machineProfile("prusa-mk4s")).map((preset) => preset.name);
        const standard = prusaPresets("print", machineProfile("prusa-mk3s")).map((preset) => preset.name);
        expect(fast).toEqual(["0.15mm SPEED", "0.20mm SPEED", "0.20mm STRUCTURAL", "0.25mm SPEED"]);
        expect(standard).toEqual(["0.10mm DETAIL", "0.15mm QUALITY", "0.20mm QUALITY", "0.30mm DRAFT"]);
        expect(prusaPresets("print").some((preset) => preset.name.startsWith("*"))).toBe(false);
        expect(prusaPresets("filament").map((preset) => preset.name)).toEqual(
            expect.arrayContaining(["Generic ASA", "Generic PETG", "Generic PLA"]),
        );
    });

    test("a job merges print, filament and printer presets with ids and overrides", () => {
        const machine = machineProfile("prusa-mk4s")!;
        const job = ok(resolvePrusaJob(machine, { overrides: { perimeters: 3, support_material: true } }));
        expect(job.printPreset).toBe("0.20mm SPEED");
        expect(job.filamentPreset).toBe("Generic PLA");
        expect(job.config["print_settings_id"]).toBe("0.20mm SPEED");
        expect(job.config["filament_settings_id"]).toBe('"Generic PLA"');
        expect(job.config["printer_settings_id"]).toBe("Original Prusa MK4S 0.4 nozzle");
        expect(job.config["perimeter_speed"]).toBe("120");
        expect(job.config["temperature"]).toBe("210");
        expect(job.config["printer_model"]).toBe("MK4S");
        expect(job.config["perimeters"]).toBe("3");
        expect(job.config["support_material"]).toBe("1");
        expect(job.config["compatible_printers_condition"]).toBeUndefined();
        expect(job.config["inherits"]).toBeUndefined();
        expect(job.warnings).toEqual([]);
    });

    test("an incompatible or unknown preset is used or skipped with a warning", () => {
        const machine = machineProfile("prusa-mk4s")!;
        const job = ok(resolvePrusaJob(machine, { print: "0.20mm QUALITY", filament: "Nope" }));
        expect(job.printPreset).toBe("0.20mm QUALITY");
        expect(job.filamentPreset).toBe("Generic PLA");
        expect(job.warnings).toEqual([
            'print preset "0.20mm QUALITY" is not marked compatible with "Original Prusa MK4S 0.4 nozzle"',
            'unknown filament preset "Nope"',
        ]);
        expect(resolvePrusaJob({ ...machine, kind: "mill" }).isOk).toBe(false);
    });
});

describe("imported bundles", () => {
    test("printers become machine profiles; listed compatible printers gate filaments", () => {
        const imported = ok(importPrusaConfig(BUNDLE));
        expect(imported.machines.map((machine) => machine.id)).toEqual(["prusaslicer-test-one-0-4"]);
        const machine = machineProfile("prusaslicer-test-one-0-4")!;
        expect(machine.vendor).toBe("Test Vendor");
        expect(machine.printer?.flavor).toBe("marlin");
        expect(machine.printer?.maxHeight).toBe(180);
        const filament = prusaPreset("filament", "Brand PLA")!;
        expect(isPresetCompatible(filament, "Test One 0.4", printerConfigOf(machine))).toBe(true);
        expect(isPresetCompatible(filament, "Other", printerConfigOf(machine))).toBe(false);
    });

    test("Klipper and RepRapFirmware presets map to their flavors and posts", () => {
        const bundle = ok(
            parsePrusaBundle(
                [
                    "[printer:K]",
                    "gcode_flavor = klipper",
                    "bed_shape = -150x-150,150x-150,150x150,-150x150",
                    "[printer:R]",
                    "gcode_flavor = reprapfirmware",
                ].join("\n"),
            ),
        );
        const klipper = machineFromPrinterPreset(bundle.printers.get("K")!, bundle);
        expect(klipper.printer?.flavor).toBe("klipper");
        expect(klipper.post.id).toBe("klipper");
        expect(klipper.linearAxes[0]).toEqual({ name: "X", min: -150, max: 150 });
        expect(klipper.printer?.bed).toEqual({ x: 300, y: 300, shape: "rectangle" });
        const rrf = machineFromPrinterPreset(bundle.printers.get("R")!, bundle);
        expect(rrf.printer?.flavor).toBe("reprapfirmware");
        expect(rrf.post.id).toBe("marlin");
    });

    test("a machine without a preset gets a printer config from its printer data", () => {
        const base = machineProfile("creality-ender-3")!;
        const machine = {
            ...base,
            post: { id: "marlin", options: { startGcode: "G28\nG1 Z5" } },
        };
        const config = printerConfigOf(machine);
        expect(config["bed_shape"]).toBe("0x0,220x0,220x220,0x220");
        expect(config["gcode_flavor"]).toBe("marlin2");
        expect(config["start_gcode"]).toBe("G28\\nG1 Z5");
    });
});
