// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import JSZip from "jszip";
import { exportPrusaProject, machineProfile, prusaJobIni, resolvePrusaJob } from "../../src";
import { ok, printerContext } from "./context";
import { boxMesh, cylinderMesh } from "./meshes";

/**
 * PrusaSlicer's reader of `Metadata/Slic3r_PE.config` (`ConfigBase::load_from_gcode_string_legacy`),
 * ported: from the last line upwards, `; key = value` lines of at least 10 characters with a
 * key of 3+ `[A-Za-z0-9_]` (starting with a letter), stopping at the first other line; blank
 * lines are skipped and the first line is never read.
 */
function readLikePrusaSlicer(text: string): Record<string, string> {
    const lines = text.split("\n");
    const out: Record<string, string> = {};
    for (let i = lines.length - 1; i >= 1; i--) {
        const line = lines[i].replace(/\r$/, "");
        if (line === "") continue;
        const match = /^; ([A-Za-z][A-Za-z0-9_]*) = (.*)$/.exec(line);
        if (line.length < 10 || !match || match[1].length < 3) break;
        out[match[1]] = match[2];
    }
    return out;
}

async function unzip(bytes: Uint8Array): Promise<Record<string, string>> {
    const zip = await JSZip.loadAsync(bytes);
    const files: Record<string, string> = {};
    for (const [name, entry] of Object.entries(zip.files))
        if (!entry.dir) files[name] = await entry.async("string");
    return files;
}

const count = (text: string, tag: string) => (text.match(new RegExp(`<${tag} `, "g")) ?? []).length;

describe("PrusaSlicer project 3MF", () => {
    test("a box: welded mesh centred on its item, the job's config, the object's settings", async () => {
        const context = printerContext("prusa-mk4s", boxMesh(100, 90, 0, 120, 110, 10));
        const bytes = await exportPrusaProject(context, {
            print: "0.20mm STRUCTURAL",
            overrides: { brim_width: 3 },
            objectSettings: [{ perimeters: 4 }],
            objectNames: ["Bracket <A>"],
        });
        const files = await unzip(bytes);
        expect(Object.keys(files).sort()).toEqual([
            "3D/3dmodel.model",
            "Metadata/Slic3r_PE.config",
            "Metadata/Slic3r_PE_model.config",
            "[Content_Types].xml",
            "_rels/.rels",
        ]);
        const model = files["3D/3dmodel.model"];
        expect(model).toContain('xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06"');
        expect(model).toContain('<metadata name="slic3rpe:Version3mf">1</metadata>');
        expect(model).toContain('unit="millimeter"');
        // 36 B-rep triangle corners weld into the box's 8 vertices.
        expect(count(model, "vertex")).toBe(8);
        expect(count(model, "triangle")).toBe(12);
        const xs = [...model.matchAll(/<vertex x="([^"]+)" y="([^"]+)" z="([^"]+)"/g)].map((m) =>
            m.slice(1).map(Number),
        );
        expect(new Set(xs.map((v) => v[0]))).toEqual(new Set([-10, 10]));
        expect(new Set(xs.map((v) => v[1]))).toEqual(new Set([-10, 10]));
        expect(new Set(xs.map((v) => v[2]))).toEqual(new Set([0, 10]));
        expect(model).toContain('<item objectid="1" transform="1 0 0 0 1 0 0 0 1 110 100 0" printable="1"/>');
        expect(files["_rels/.rels"]).toContain('Target="/3D/3dmodel.model"');

        const objectConfig = files["Metadata/Slic3r_PE_model.config"];
        expect(objectConfig).toContain('<object id="1" instances_count="1">');
        expect(objectConfig).toContain('<metadata type="object" key="name" value="Bracket &lt;A&gt;"/>');
        expect(objectConfig).toContain('<metadata type="object" key="perimeters" value="4"/>');
        expect(objectConfig).toContain('<volume firstid="0" lastid="11">');
        expect(objectConfig).toContain('<metadata type="volume" key="volume_type" value="ModelPart"/>');

        const config = files["Metadata/Slic3r_PE.config"];
        expect(config.split("\n")[0]).toMatch(
            /^; generated by Chili3d on \d{4}-\d\d-\d\d at \d\d:\d\d:\d\d UTC$/,
        );
        const job = ok(
            resolvePrusaJob(machineProfile("prusa-mk4s")!, {
                print: "0.20mm STRUCTURAL",
                overrides: { brim_width: 3 },
            }),
        );
        const read = readLikePrusaSlicer(config);
        // PrusaSlicer reads every key back (no line ends its scan early).
        const exported = Object.keys(job.config).filter((key) => !key.startsWith("chili3d_"));
        expect(Object.keys(read).sort()).toEqual(exported.sort());
        expect(read["print_settings_id"]).toBe("0.20mm STRUCTURAL");
        expect(read["filament_settings_id"]).toBe('"Generic PLA"');
        expect(read["printer_settings_id"]).toBe("Original Prusa MK4S 0.4 nozzle");
        expect(read["perimeters"]).toBe("3");
        expect(read["fill_pattern"]).toBe("gyroid");
        expect(read["brim_width"]).toBe("3");
        expect(read["bed_shape"]).toBe("0x0,250x0,250x210,0x210");
        expect(read["start_gcode"]).toContain('M862.3 P "[printer_model]" ; printer model check\\nM862.1');
        expect(read["chili3d_machine_id"]).toBeUndefined();
    });

    test("several parts are several objects, named after their nodes", async () => {
        const context = printerContext("prusa-mk3s", boxMesh(0, 0, 0, 1, 1, 1), {
            parts: [
                { id: "a", name: "Left", mesh: boxMesh(50, 50, 0, 60, 60, 5) },
                { id: "b", name: "Right", mesh: cylinderMesh(150, 100, 8, 0, 12, 32) },
            ],
        });
        const files = await unzip(await exportPrusaProject(context));
        const model = files["3D/3dmodel.model"];
        expect(count(model, "object")).toBe(2);
        expect(model).toContain('<item objectid="1" transform="1 0 0 0 1 0 0 0 1 55 55 0" printable="1"/>');
        expect(model).toContain('<item objectid="2" transform="1 0 0 0 1 0 0 0 1 150 100 0" printable="1"/>');
        // A closed 32-facet cylinder: 2 × 32 rim vertices and the two cap centres.
        const second = model.slice(model.indexOf('<object id="2"'));
        expect(count(second, "vertex")).toBe(66);
        expect(count(second, "triangle")).toBe(128);
        const objectConfig = files["Metadata/Slic3r_PE_model.config"];
        expect(objectConfig).toContain('key="name" value="Left"');
        expect(objectConfig).toContain('key="name" value="Right"');
        expect(readLikePrusaSlicer(files["Metadata/Slic3r_PE.config"])["printer_settings_id"]).toBe(
            "Original Prusa i3 MK3S & MK3S+",
        );
    });

    test("parts off the bed are centred; parts too large or a non-printer are refused", async () => {
        const off = await unzip(
            await exportPrusaProject(printerContext("prusa-mk4s", boxMesh(-50, -50, 3, -30, -30, 8))),
        );
        expect(off["3D/3dmodel.model"]).toContain('transform="1 0 0 0 1 0 0 0 1 125 105 0"');
        expect(off["3D/3dmodel.model"]).toMatch(/z="0"/);
        await expect(
            exportPrusaProject(printerContext("prusa-mini", boxMesh(0, 0, 0, 200, 10, 10))),
        ).rejects.toThrow("do not fit");
        const context = printerContext("prusa-mk4s", boxMesh(0, 0, 0, 10, 10, 10));
        await expect(
            exportPrusaProject({ ...context, machine: { ...context.machine, kind: "mill" } }),
        ).rejects.toThrow("not a 3D printer");
    });

    test("the job INI for prusa-slicer --load is plain key = value, without Chili3d keys", () => {
        const job = ok(resolvePrusaJob(machineProfile("voron-2-4-350")!, {}));
        const ini = prusaJobIni(job, new Date("2026-01-02T03:04:05Z"));
        const lines = ini.trim().split("\n");
        expect(lines[0]).toBe("# generated by Chili3d on 2026-01-02 at 03:04:05 UTC");
        const keys = lines.slice(1).map((line) => line.split(" = ")[0]);
        expect(keys).toEqual([...keys].sort());
        expect(new Set(keys).size).toBe(keys.length);
        expect(lines).toContain("gcode_flavor = klipper");
        expect(lines).toContain("binary_gcode = 0");
        expect(lines).toContain("print_settings_id = 0.20mm SPEED");
        expect(keys.some((key) => key.startsWith("chili3d_"))).toBe(false);
    });
});
