// Part of the Chili3d Project, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

/**
 * Reference data for the function browser: an Excel-style category, a signature, a
 * one-line description, an example and argument notes for (far) more functions than the
 * engine evaluates. `functionInfo.ts` merges it with the evaluator's own metadata; the
 * browser lists only names in `FORMULA_FUNCTIONS`, so an entry here never advertises an
 * unsupported function. Pure data: no imports, so any module may use it without cycles.
 */

export const FUNCTION_CATEGORIES = [
    "Math & trig",
    "Statistical",
    "Logical",
    "Text",
    "Date & time",
    "Lookup & reference",
    "Array",
    "Financial",
    "Information",
    "Engineering",
    "Database",
    "Other",
] as const;
export type FunctionCategory = (typeof FUNCTION_CATEGORIES)[number];

/** [signature, description, example, argument notes by parameter name (digits and brackets stripped)]. */
type Row = readonly [signature: string, description: string, example: string, args?: Record<string, string>];

export interface FunctionDetail {
    category: FunctionCategory;
    signature: string;
    description: string;
    example: string;
    args?: Record<string, string>;
}

/** Notes for parameter names shared by many functions; a function's own notes take precedence. */
export const ARGUMENT_DOCS: Record<string, string> = {
    number: "A number, a cell reference or a range of numbers.",
    value: "A value, cell reference or range.",
    text: "Text, or a reference to a cell containing text.",
    logical: "A condition that evaluates to TRUE or FALSE.",
    logical_test: "A condition that evaluates to TRUE or FALSE, e.g. A1>10.",
    value_if_true: "Returned when the condition is TRUE.",
    value_if_false: "Returned when the condition is FALSE (default FALSE).",
    value_if_error: "Returned when the value is an error.",
    value_if_na: "Returned when the value is #N/A.",
    range: "The cells to test.",
    criteria: 'The condition, e.g. 10, ">5", "apple" or "a*" (wildcards * and ?).',
    criteria_range: "A range tested against the criteria that follows it.",
    sum_range: "The cells to add (default: the tested range).",
    average_range: "The cells to average (default: the tested range).",
    min_range: "The cells from which the minimum is taken.",
    max_range: "The cells from which the maximum is taken.",
    array: "A range or array of values.",
    lookup_value: "The value to look for.",
    lookup_array: "The row or column searched.",
    lookup_vector: "The row or column searched.",
    result_vector: "The row or column returned from (same size as the lookup vector).",
    return_array: "The row, column or range returned from.",
    table_array: "The table whose first column (or row) is searched.",
    col_index_num: "The 1-based column of the table to return.",
    row_index_num: "The 1-based row of the table to return.",
    range_lookup: "FALSE for an exact match; TRUE (default) for the nearest smaller value in sorted data.",
    match_type: "0 exact, 1 largest value ≤ (sorted ascending), -1 smallest value ≥ (sorted descending).",
    match_mode: "0 exact (default), -1 exact or next smaller, 1 exact or next larger, 2 wildcard.",
    search_mode: "1 first to last (default), -1 last to first, 2 / -2 binary search.",
    if_not_found: "Returned when nothing matches (default #N/A).",
    row_num: "The 1-based row number.",
    column_num: "The 1-based column number.",
    col_num: "The 1-based column number.",
    reference: "A cell or range reference.",
    serial_number: "A date or time serial number, or a reference to one.",
    start_date: "The first date.",
    end_date: "The last date.",
    date: "A date serial number.",
    months: "The number of months before (negative) or after the date.",
    days: "The number of days.",
    holidays: "Optional dates to exclude, as a range or array.",
    weekend: 'Which days are weekends: 1 (Sat–Sun, default) … 17, or a mask like "0000011".',
    return_type: "Selects the numbering scheme.",
    basis: "Day count: 0 US 30/360 (default), 1 actual/actual, 2 actual/360, 3 actual/365, 4 European 30/360.",
    rate: "The interest rate per period (e.g. 5%/12 for monthly payments at 5% a year).",
    nper: "The total number of payment periods.",
    pmt: "The payment made each period (negative for money paid out).",
    pv: "The present value: what the future payments are worth now.",
    fv: "The future value after the last payment (default 0).",
    type: "When payments are due: 0 end of period (default), 1 beginning.",
    per: "The period of interest, from 1 to nper.",
    guess: "A starting estimate for the iteration (default 10%).",
    values: "The cash flows, negative for payments and positive for income.",
    dates: "The payment dates matching the values.",
    settlement: "The security's settlement date.",
    maturity: "The security's maturity date.",
    frequency: "Coupon payments per year: 1 annual, 2 semiannual, 4 quarterly.",
    redemption: "The redemption value per $100 face value.",
    cost: "The initial cost of the asset.",
    salvage: "The value at the end of depreciation.",
    life: "The number of periods over which the asset depreciates.",
    period: "The period for which depreciation is calculated.",
    significance: "The multiple to round to.",
    mode: "Direction for negative numbers (nonzero rounds away from zero).",
    num_digits: "The number of decimal places (negative rounds left of the decimal point).",
    num_chars: "The number of characters.",
    start_num: "The 1-based character position to start at.",
    find_text: "The text to find.",
    within_text: "The text to search in.",
    old_text: "The text to change.",
    new_text: "The replacement text.",
    instance_num: "Which occurrence to use (default: every one).",
    delimiter: "The text placed between (or splitting) items.",
    ignore_empty: "TRUE to skip empty cells.",
    format_text: 'A number format in quotes, e.g. "0.00" or "yyyy-mm-dd".',
    decimals: "The number of decimal places.",
    k: "The position (from the largest or smallest) to return.",
    alpha: "The significance level (e.g. 0.05).",
    mean: "The arithmetic mean of the distribution.",
    standard_dev: "The standard deviation of the distribution.",
    cumulative: "TRUE for the cumulative distribution, FALSE for the density / mass.",
    x: "The value at which to evaluate.",
    deg_freedom: "The degrees of freedom.",
    probability: "A probability between 0 and 1.",
    known_ys: "The dependent (y) values.",
    known_xs: "The independent (x) values.",
    new_xs: "The x values to predict for.",
    const: "FALSE forces the intercept to zero (default TRUE).",
    stats: "TRUE also returns regression statistics.",
    trials: "The number of independent trials.",
    probability_s: "The probability of success in each trial.",
    number_s: "The number of successes.",
    tails: "1 for a one-tailed test, 2 for two-tailed.",
    inumber: 'A complex number as text, e.g. "3+4i".',
    places: "The minimum number of digits (padded with leading zeros).",
    radix: "The base, from 2 to 36.",
    database: "The range holding the list, with column labels in its first row.",
    field: "The column to use: its label in quotes or its 1-based position.",
    function_num:
        "Which aggregate: 1 AVERAGE, 2 COUNT, 3 COUNTA, 4 MAX, 5 MIN, 9 SUM… (101–111 skip hidden rows).",
    rows: "The number of rows.",
    columns: "The number of columns.",
    start: "The first number (default 1).",
    step: "The increment between numbers (default 1).",
    include: "A TRUE/FALSE array as tall (or wide) as the array, selecting what to keep.",
    if_empty: "Returned when nothing is kept (default #CALC!).",
    sort_index: "The row or column to sort by (default 1).",
    sort_order: "1 ascending (default), -1 descending.",
    by_col: "TRUE to work on columns instead of rows.",
    exactly_once: "TRUE to return only values that occur exactly once.",
    by_array: "The range or array to sort by.",
    pad_with: "The value used to fill missing cells (default #N/A).",
    wrap_count: "The number of values per row or column.",
    name: "A name to assign; it can be used in later arguments.",
    name_value: "The value assigned to the name.",
    calculation: "The formula that uses the names; its value is the result.",
    lambda: "A LAMBDA applied to each item.",
    expression: "The value to compare.",
    index_num: "Which value to return, from 1.",
    bottom: "The smallest integer returned.",
    top: "The largest integer returned.",
    numerator: "The dividend.",
    denominator: "The divisor.",
    multiple: "The multiple to round to.",
    base: "The base of the logarithm.",
    power: "The exponent.",
    divisor: "The number to divide by.",
    angle: "An angle.",
    hour: "The hour, 0 to 23.",
    minute: "The minute, 0 to 59.",
    second: "The second, 0 to 59.",
    year: "The year, e.g. 2024.",
    month: "The month, 1 to 12 (larger values roll into later years).",
    day: "The day of the month (overflows roll into later months).",
    ref_text: 'A reference as text, e.g. "B3" or "Sheet2!A1:A10".',
    a1: "TRUE (default) for A1 style, FALSE for R1C1.",
    height: "The height of the returned range in rows.",
    width: "The width of the returned range in columns.",
    quart: "0 minimum, 1 first quartile, 2 median, 3 third quartile, 4 maximum.",
    percent: "The fraction of points to exclude.",
    order: "0 (default) ranks largest first, nonzero smallest first.",
    significance_digits: "The number of significant digits.",
    number_chosen: "The number of items in each combination.",
    shift_amount: "The number of bits to shift.",
    from_unit: 'The unit of the number, e.g. "mm".',
    to_unit: 'The unit of the result, e.g. "in".',
    lower_limit: "The lower bound of integration.",
    upper_limit: "The upper bound of integration.",
    real_num: "The real coefficient.",
    i_num: "The imaginary coefficient.",
    n: "The order.",
    principal: "The present value.",
    schedule: "An array of interest rates to apply.",
    npery: "The number of compounding periods per year.",
    start_period: "The first period in the calculation.",
    end_period: "The last period in the calculation.",
    factor: "The rate at which the balance declines (default 2, double-declining).",
    no_switch: "TRUE to never switch to straight-line depreciation.",
    finance_rate: "The interest rate paid on money used in the cash flows.",
    reinvest_rate: "The interest rate earned on reinvested cash flows.",
    issue: "The security's issue date.",
    par: "The security's par value (default $1,000).",
    pr: "The security's price per $100 face value.",
    yld: "The security's annual yield.",
    discount: "The security's discount rate.",
    investment: "The amount invested.",
    unit: '"Y", "M", "D", "MD", "YM" or "YD".',
    date_text: 'A date as text, e.g. "2024-03-15".',
    time_text: 'A time as text, e.g. "6:45 PM".',
    info_type: 'The kind of information, e.g. "address", "row", "col", "contents" or "type".',
    error_val: "The error value to identify.",
    data_array: "The values to count.",
    bins_array: "The upper bounds of the intervals.",
    actual_range: "The observed values.",
    expected_range: "The expected values.",
    size: "The sample size.",
    z: "The value of the standard normal variable.",
    lambda_rate: "The rate parameter.",
    order_by: "The values that set the order.",
};

const MATH: Record<string, Row> = {
    ABS: ["number", "Returns the absolute value of a number.", "=ABS(-4)"],
    ACOS: ["number", "Returns the inverse cosine, in radians.", "=ACOS(0.5)"],
    ACOSH: ["number", "Returns the inverse hyperbolic cosine.", "=ACOSH(1.5)"],
    ACOT: ["number", "Returns the inverse cotangent, in radians.", "=ACOT(2)"],
    ACOTH: ["number", "Returns the inverse hyperbolic cotangent.", "=ACOTH(6)"],
    AGGREGATE: [
        "function_num, options, ref1, [ref2], …",
        "Aggregates a range, optionally ignoring hidden rows and errors.",
        "=AGGREGATE(9, 6, A1:A10)",
        { options: "What to ignore: 0–7, e.g. 6 ignores error values." },
    ],
    ARABIC: ["text", "Converts a Roman numeral to a number.", '=ARABIC("MCMXC")'],
    ASIN: ["number", "Returns the inverse sine, in radians.", "=ASIN(1)"],
    ASINH: ["number", "Returns the inverse hyperbolic sine.", "=ASINH(1)"],
    ATAN: ["number", "Returns the inverse tangent, in radians.", "=ATAN(1)"],
    ATAN2: [
        "x_num, y_num",
        "Returns the angle of the point (x, y) from the x-axis, in radians.",
        "=ATAN2(1, 1)",
        { x_num: "The x coordinate.", y_num: "The y coordinate." },
    ],
    ATANH: ["number", "Returns the inverse hyperbolic tangent.", "=ATANH(0.5)"],
    BASE: [
        "number, radix, [min_length]",
        "Converts a number to text in another base.",
        "=BASE(255, 16)",
        { min_length: "The minimum length, padded with zeros." },
    ],
    CEILING: [
        "number, significance",
        "Rounds up to the nearest multiple of significance.",
        "=CEILING(4.3, 0.5)",
    ],
    "CEILING.MATH": [
        "number, [significance], [mode]",
        "Rounds up to the nearest integer or multiple.",
        "=CEILING.MATH(-4.3)",
    ],
    "CEILING.PRECISE": [
        "number, [significance]",
        "Rounds up to a multiple, regardless of sign.",
        "=CEILING.PRECISE(-4.3, 2)",
    ],
    COMBIN: ["number, number_chosen", "Returns the number of combinations.", "=COMBIN(8, 2)"],
    COMBINA: ["number, number_chosen", "Returns combinations with repetitions.", "=COMBINA(4, 3)"],
    COS: ["number", "Returns the cosine of an angle in radians.", "=COS(PI())"],
    COSH: ["number", "Returns the hyperbolic cosine.", "=COSH(1)"],
    COT: ["number", "Returns the cotangent of an angle in radians.", "=COT(1)"],
    COTH: ["number", "Returns the hyperbolic cotangent.", "=COTH(1)"],
    CSC: ["number", "Returns the cosecant of an angle in radians.", "=CSC(1)"],
    CSCH: ["number", "Returns the hyperbolic cosecant.", "=CSCH(1)"],
    DECIMAL: ["text, radix", "Converts text in a given base to a number.", '=DECIMAL("FF", 16)'],
    DEGREES: ["angle", "Converts radians to degrees.", "=DEGREES(PI())"],
    EVEN: ["number", "Rounds away from zero to the nearest even integer.", "=EVEN(3.2)"],
    EXP: ["number", "Returns e raised to a power.", "=EXP(1)"],
    FACT: ["number", "Returns the factorial of a number.", "=FACT(5)"],
    FACTDOUBLE: ["number", "Returns the double factorial of a number.", "=FACTDOUBLE(7)"],
    FLOOR: [
        "number, significance",
        "Rounds down to the nearest multiple of significance.",
        "=FLOOR(4.7, 0.5)",
    ],
    "FLOOR.MATH": [
        "number, [significance], [mode]",
        "Rounds down to the nearest integer or multiple.",
        "=FLOOR.MATH(-4.3)",
    ],
    "FLOOR.PRECISE": [
        "number, [significance]",
        "Rounds down to a multiple, regardless of sign.",
        "=FLOOR.PRECISE(-4.3, 2)",
    ],
    GCD: ["number1, [number2], …", "Returns the greatest common divisor.", "=GCD(24, 36)"],
    INT: ["number", "Rounds down to the nearest integer.", "=INT(-3.7)"],
    "ISO.CEILING": [
        "number, [significance]",
        "Rounds up to a multiple, regardless of sign.",
        "=ISO.CEILING(4.3)",
    ],
    LCM: ["number1, [number2], …", "Returns the least common multiple.", "=LCM(4, 6)"],
    LN: ["number", "Returns the natural logarithm.", "=LN(10)"],
    LOG: ["number, [base]", "Returns the logarithm in a base (default 10).", "=LOG(8, 2)"],
    LOG10: ["number", "Returns the base-10 logarithm.", "=LOG10(1000)"],
    MDETERM: ["array", "Returns the determinant of a square matrix.", "=MDETERM(A1:C3)"],
    MINVERSE: ["array", "Returns the inverse of a square matrix.", "=MINVERSE(A1:B2)"],
    MMULT: ["array1, array2", "Returns the matrix product of two arrays.", "=MMULT(A1:B2, D1:E2)"],
    MOD: ["number, divisor", "Returns the remainder of a division.", "=MOD(10, 3)"],
    MROUND: ["number, multiple", "Rounds to the nearest multiple.", "=MROUND(17, 5)"],
    MULTINOMIAL: ["number1, [number2], …", "Returns the multinomial coefficient.", "=MULTINOMIAL(2, 3, 4)"],
    MUNIT: [
        "dimension",
        "Returns an identity matrix.",
        "=MUNIT(3)",
        { dimension: "The size of the matrix." },
    ],
    ODD: ["number", "Rounds away from zero to the nearest odd integer.", "=ODD(2.1)"],
    PI: ["", "Returns π to 15 digits.", "=PI()*A1^2"],
    POWER: ["number, power", "Raises a number to a power.", "=POWER(2, 10)"],
    PRODUCT: ["number1, [number2], …", "Multiplies numbers and ranges.", "=PRODUCT(A1:A4)"],
    QUOTIENT: ["numerator, denominator", "Returns the integer part of a division.", "=QUOTIENT(10, 3)"],
    RADIANS: ["angle", "Converts degrees to radians.", "=RADIANS(180)"],
    RAND: ["", "Returns a random number between 0 and 1.", "=RAND()"],
    RANDARRAY: [
        "[rows], [columns], [min], [max], [whole_number]",
        "Returns an array of random numbers.",
        "=RANDARRAY(5, 1, 1, 100, TRUE)",
        {
            min: "The smallest number (default 0).",
            max: "The largest number (default 1).",
            whole_number: "TRUE for integers, FALSE (default) for decimals.",
        },
    ],
    RANDBETWEEN: ["bottom, top", "Returns a random integer between two numbers.", "=RANDBETWEEN(1, 6)"],
    ROMAN: [
        "number, [form]",
        "Converts a number to a Roman numeral.",
        "=ROMAN(1990)",
        { form: "0 (classic) to 4 (most concise)." },
    ],
    ROUND: ["number, num_digits", "Rounds a number to a number of digits.", "=ROUND(3.14159, 2)"],
    ROUNDDOWN: ["number, num_digits", "Rounds a number toward zero.", "=ROUNDDOWN(3.789, 1)"],
    ROUNDUP: ["number, num_digits", "Rounds a number away from zero.", "=ROUNDUP(3.211, 1)"],
    SEC: ["number", "Returns the secant of an angle in radians.", "=SEC(1)"],
    SECH: ["number", "Returns the hyperbolic secant.", "=SECH(1)"],
    SEQUENCE: [
        "rows, [columns], [start], [step]",
        "Returns a sequence of numbers that spills into neighbouring cells.",
        "=SEQUENCE(10)",
    ],
    SERIESSUM: [
        "x, n, m, coefficients",
        "Returns the sum of a power series.",
        "=SERIESSUM(0.5, 0, 1, A1:A4)",
        {
            n: "The initial power.",
            m: "The step added to n for each term.",
            coefficients: "The coefficients.",
        },
    ],
    SIGN: ["number", "Returns -1, 0 or 1 for the sign of a number.", "=SIGN(-5)"],
    SIN: ["number", "Returns the sine of an angle in radians.", "=SIN(RADIANS(30))"],
    SINH: ["number", "Returns the hyperbolic sine.", "=SINH(1)"],
    SQRT: ["number", "Returns the positive square root.", "=SQRT(16)"],
    SQRTPI: ["number", "Returns the square root of number × π.", "=SQRTPI(2)"],
    SUBTOTAL: [
        "function_num, ref1, [ref2], …",
        "Aggregates a range, ignoring other SUBTOTALs (101–111 skip hidden rows).",
        "=SUBTOTAL(109, B2:B20)",
    ],
    SUM: ["number1, [number2], …", "Adds numbers, cell references and ranges.", "=SUM(A1:A10)"],
    SUMIF: [
        "range, criteria, [sum_range]",
        "Adds the cells that meet one condition.",
        '=SUMIF(A2:A10, ">5")',
    ],
    SUMIFS: [
        "sum_range, criteria_range1, criteria1, …",
        "Adds the cells that meet every condition.",
        '=SUMIFS(C2:C10, A2:A10, "East", B2:B10, ">100")',
    ],
    SUMPRODUCT: [
        "array1, [array2], …",
        "Multiplies matching items of arrays and adds the products.",
        "=SUMPRODUCT(B2:B5, C2:C5)",
    ],
    SUMSQ: ["number1, [number2], …", "Returns the sum of the squares.", "=SUMSQ(3, 4)"],
    SUMX2MY2: [
        "array_x, array_y",
        "Sums the differences of squares of matching values.",
        "=SUMX2MY2(A1:A5, B1:B5)",
        { array_x: "The first array.", array_y: "The second array." },
    ],
    SUMX2PY2: [
        "array_x, array_y",
        "Sums the sums of squares of matching values.",
        "=SUMX2PY2(A1:A5, B1:B5)",
        { array_x: "The first array.", array_y: "The second array." },
    ],
    SUMXMY2: [
        "array_x, array_y",
        "Sums the squared differences of matching values.",
        "=SUMXMY2(A1:A5, B1:B5)",
        { array_x: "The first array.", array_y: "The second array." },
    ],
    TAN: ["number", "Returns the tangent of an angle in radians.", "=TAN(RADIANS(45))"],
    TANH: ["number", "Returns the hyperbolic tangent.", "=TANH(0.5)"],
    TRUNC: ["number, [num_digits]", "Truncates a number toward zero.", "=TRUNC(8.97, 1)"],
};

const STATISTICAL: Record<string, Row> = {
    AVEDEV: [
        "number1, [number2], …",
        "Returns the average absolute deviation from the mean.",
        "=AVEDEV(A1:A10)",
    ],
    AVERAGE: ["number1, [number2], …", "Returns the arithmetic mean.", "=AVERAGE(B2:B20)"],
    AVERAGEA: [
        "value1, [value2], …",
        "Averages values, counting text as 0 and TRUE as 1.",
        "=AVERAGEA(A1:A10)",
    ],
    AVERAGEIF: [
        "range, criteria, [average_range]",
        "Averages the cells that meet one condition.",
        '=AVERAGEIF(A2:A10, "East", B2:B10)',
    ],
    AVERAGEIFS: [
        "average_range, criteria_range1, criteria1, …",
        "Averages the cells that meet every condition.",
        '=AVERAGEIFS(C2:C10, A2:A10, "East", B2:B10, ">0")',
    ],
    "BETA.DIST": [
        "x, alpha, beta, cumulative, [A], [B]",
        "Returns the beta distribution.",
        "=BETA.DIST(0.4, 2, 3, TRUE)",
        {
            alpha: "The alpha shape parameter.",
            beta: "The beta shape parameter.",
            A: "Lower bound.",
            B: "Upper bound.",
        },
    ],
    "BETA.INV": [
        "probability, alpha, beta, [A], [B]",
        "Returns the inverse of the cumulative beta distribution.",
        "=BETA.INV(0.5, 2, 3)",
        { alpha: "The alpha shape parameter.", beta: "The beta shape parameter." },
    ],
    "BINOM.DIST": [
        "number_s, trials, probability_s, cumulative",
        "Returns the binomial distribution probability.",
        "=BINOM.DIST(6, 10, 0.5, FALSE)",
    ],
    "BINOM.DIST.RANGE": [
        "trials, probability_s, number_s, [number_s2]",
        "Returns the probability of a number of successes in a range.",
        "=BINOM.DIST.RANGE(60, 0.75, 45, 50)",
    ],
    "BINOM.INV": [
        "trials, probability_s, alpha",
        "Returns the smallest k whose cumulative binomial probability is at least alpha.",
        "=BINOM.INV(6, 0.5, 0.75)",
    ],
    "CHISQ.DIST": [
        "x, deg_freedom, cumulative",
        "Returns the chi-squared distribution.",
        "=CHISQ.DIST(0.5, 1, TRUE)",
    ],
    "CHISQ.DIST.RT": [
        "x, deg_freedom",
        "Returns the right-tailed chi-squared probability.",
        "=CHISQ.DIST.RT(3, 4)",
    ],
    "CHISQ.INV": [
        "probability, deg_freedom",
        "Returns the inverse of the chi-squared distribution.",
        "=CHISQ.INV(0.9, 3)",
    ],
    "CHISQ.INV.RT": [
        "probability, deg_freedom",
        "Returns the inverse of the right-tailed chi-squared distribution.",
        "=CHISQ.INV.RT(0.05, 3)",
    ],
    "CHISQ.TEST": [
        "actual_range, expected_range",
        "Returns the chi-squared test for independence.",
        "=CHISQ.TEST(B2:C4, E2:F4)",
    ],
    "CONFIDENCE.NORM": [
        "alpha, standard_dev, size",
        "Returns the confidence interval half-width using a normal distribution.",
        "=CONFIDENCE.NORM(0.05, 2.5, 50)",
    ],
    "CONFIDENCE.T": [
        "alpha, standard_dev, size",
        "Returns the confidence interval half-width using Student's t.",
        "=CONFIDENCE.T(0.05, 1, 50)",
    ],
    CORREL: [
        "array1, array2",
        "Returns the correlation coefficient of two ranges.",
        "=CORREL(A2:A20, B2:B20)",
    ],
    COUNT: ["value1, [value2], …", "Counts the cells that contain numbers.", "=COUNT(A1:A20)"],
    COUNTA: ["value1, [value2], …", "Counts the cells that are not empty.", "=COUNTA(A1:A20)"],
    COUNTBLANK: ["range", "Counts the empty cells in a range.", "=COUNTBLANK(A1:A20)"],
    COUNTIF: ["range, criteria", "Counts the cells that meet one condition.", '=COUNTIF(A2:A20, "Yes")'],
    COUNTIFS: [
        "criteria_range1, criteria1, …",
        "Counts the rows that meet every condition.",
        '=COUNTIFS(A2:A20, "East", B2:B20, ">100")',
    ],
    COUNTUNIQUE: [
        "value1, [value2], …",
        "Counts the unique values in the arguments and ranges.",
        "=COUNTUNIQUE(A2:A50)",
    ],
    "COVARIANCE.P": ["array1, array2", "Returns the population covariance.", "=COVARIANCE.P(A2:A10, B2:B10)"],
    "COVARIANCE.S": ["array1, array2", "Returns the sample covariance.", "=COVARIANCE.S(A2:A10, B2:B10)"],
    DEVSQ: [
        "number1, [number2], …",
        "Returns the sum of squared deviations from the mean.",
        "=DEVSQ(A1:A10)",
    ],
    "EXPON.DIST": [
        "x, lambda, cumulative",
        "Returns the exponential distribution.",
        "=EXPON.DIST(0.2, 10, TRUE)",
        { lambda: "The rate parameter." },
    ],
    "F.DIST": [
        "x, deg_freedom1, deg_freedom2, cumulative",
        "Returns the F probability distribution.",
        "=F.DIST(15, 6, 4, TRUE)",
    ],
    "F.DIST.RT": [
        "x, deg_freedom1, deg_freedom2",
        "Returns the right-tailed F distribution.",
        "=F.DIST.RT(15, 6, 4)",
    ],
    "F.INV": [
        "probability, deg_freedom1, deg_freedom2",
        "Returns the inverse of the F distribution.",
        "=F.INV(0.01, 6, 4)",
    ],
    "F.INV.RT": [
        "probability, deg_freedom1, deg_freedom2",
        "Returns the inverse of the right-tailed F distribution.",
        "=F.INV.RT(0.01, 6, 4)",
    ],
    "F.TEST": ["array1, array2", "Returns the result of an F-test.", "=F.TEST(A2:A10, B2:B10)"],
    FISHER: ["x", "Returns the Fisher transformation.", "=FISHER(0.75)"],
    FISHERINV: [
        "y",
        "Returns the inverse of the Fisher transformation.",
        "=FISHERINV(0.97)",
        { y: "The value to transform." },
    ],
    FORECAST: [
        "x, known_ys, known_xs",
        "Predicts a value along a linear trend.",
        "=FORECAST(30, B2:B10, A2:A10)",
    ],
    "FORECAST.LINEAR": [
        "x, known_ys, known_xs",
        "Predicts a value along a linear trend.",
        "=FORECAST.LINEAR(30, B2:B10, A2:A10)",
    ],
    FREQUENCY: [
        "data_array, bins_array",
        "Counts how many values fall into each interval, as a vertical array.",
        "=FREQUENCY(A2:A50, C2:C6)",
    ],
    GAMMA: ["number", "Returns the gamma function value.", "=GAMMA(2.5)"],
    "GAMMA.DIST": [
        "x, alpha, beta, cumulative",
        "Returns the gamma distribution.",
        "=GAMMA.DIST(10, 9, 2, FALSE)",
        { alpha: "The shape parameter.", beta: "The scale parameter." },
    ],
    "GAMMA.INV": [
        "probability, alpha, beta",
        "Returns the inverse of the cumulative gamma distribution.",
        "=GAMMA.INV(0.07, 9, 2)",
        { alpha: "The shape parameter.", beta: "The scale parameter." },
    ],
    GAMMALN: ["x", "Returns the natural logarithm of the gamma function.", "=GAMMALN(4)"],
    "GAMMALN.PRECISE": ["x", "Returns the natural logarithm of the gamma function.", "=GAMMALN.PRECISE(4)"],
    GAUSS: ["z", "Returns 0.5 less than the standard normal cumulative distribution.", "=GAUSS(2)"],
    GEOMEAN: ["number1, [number2], …", "Returns the geometric mean.", "=GEOMEAN(A1:A10)"],
    GROWTH: [
        "known_ys, [known_xs], [new_xs], [const]",
        "Predicts exponential growth from existing data.",
        "=GROWTH(B2:B7, A2:A7, A8:A9)",
    ],
    HARMEAN: ["number1, [number2], …", "Returns the harmonic mean.", "=HARMEAN(A1:A10)"],
    "HYPGEOM.DIST": [
        "sample_s, number_sample, population_s, number_pop, cumulative",
        "Returns the hypergeometric distribution.",
        "=HYPGEOM.DIST(1, 4, 8, 20, FALSE)",
        {
            sample_s: "Successes in the sample.",
            number_sample: "The sample size.",
            population_s: "Successes in the population.",
            number_pop: "The population size.",
        },
    ],
    INTERCEPT: [
        "known_ys, known_xs",
        "Returns the y-intercept of the linear regression line.",
        "=INTERCEPT(B2:B10, A2:A10)",
    ],
    KURT: ["number1, [number2], …", "Returns the kurtosis of a data set.", "=KURT(A1:A20)"],
    LARGE: ["array, k", "Returns the k-th largest value.", "=LARGE(A1:A20, 2)"],
    LINEST: [
        "known_ys, [known_xs], [const], [stats]",
        "Returns the parameters of a linear trend fitted by least squares.",
        "=LINEST(B2:B10, A2:A10)",
    ],
    LOGEST: [
        "known_ys, [known_xs], [const], [stats]",
        "Returns the parameters of an exponential trend.",
        "=LOGEST(B2:B10, A2:A10)",
    ],
    "LOGNORM.DIST": [
        "x, mean, standard_dev, cumulative",
        "Returns the lognormal distribution.",
        "=LOGNORM.DIST(4, 3.5, 1.2, TRUE)",
    ],
    "LOGNORM.INV": [
        "probability, mean, standard_dev",
        "Returns the inverse of the lognormal distribution.",
        "=LOGNORM.INV(0.039, 3.5, 1.2)",
    ],
    MAX: ["number1, [number2], …", "Returns the largest value.", "=MAX(A1:A20)"],
    MAXA: [
        "value1, [value2], …",
        "Returns the largest value, counting text as 0 and TRUE as 1.",
        "=MAXA(A1:A20)",
    ],
    MAXIFS: [
        "max_range, criteria_range1, criteria1, …",
        "Returns the largest value that meets every condition.",
        '=MAXIFS(C2:C20, A2:A20, "East")',
    ],
    MEDIAN: ["number1, [number2], …", "Returns the middle value.", "=MEDIAN(A1:A20)"],
    MIN: ["number1, [number2], …", "Returns the smallest value.", "=MIN(A1:A20)"],
    MINA: [
        "value1, [value2], …",
        "Returns the smallest value, counting text as 0 and TRUE as 1.",
        "=MINA(A1:A20)",
    ],
    MINIFS: [
        "min_range, criteria_range1, criteria1, …",
        "Returns the smallest value that meets every condition.",
        '=MINIFS(C2:C20, A2:A20, "East")',
    ],
    MODE: ["number1, [number2], …", "Returns the most frequent value.", "=MODE(A1:A20)"],
    "MODE.MULT": [
        "number1, [number2], …",
        "Returns every most-frequent value, as a vertical array.",
        "=MODE.MULT(A1:A20)",
    ],
    "MODE.SNGL": ["number1, [number2], …", "Returns the most frequent value.", "=MODE.SNGL(A1:A20)"],
    "NEGBINOM.DIST": [
        "number_f, number_s, probability_s, cumulative",
        "Returns the negative binomial distribution.",
        "=NEGBINOM.DIST(10, 5, 0.25, FALSE)",
        { number_f: "The number of failures." },
    ],
    "NORM.DIST": [
        "x, mean, standard_dev, cumulative",
        "Returns the normal distribution.",
        "=NORM.DIST(42, 40, 1.5, TRUE)",
    ],
    "NORM.INV": [
        "probability, mean, standard_dev",
        "Returns the inverse of the normal cumulative distribution.",
        "=NORM.INV(0.908, 40, 1.5)",
    ],
    "NORM.S.DIST": ["z, cumulative", "Returns the standard normal distribution.", "=NORM.S.DIST(1.33, TRUE)"],
    "NORM.S.INV": [
        "probability",
        "Returns the inverse of the standard normal distribution.",
        "=NORM.S.INV(0.908)",
    ],
    PEARSON: ["array1, array2", "Returns the Pearson correlation coefficient.", "=PEARSON(A2:A10, B2:B10)"],
    PERCENTILE: ["array, k", "Returns the k-th percentile (k from 0 to 1).", "=PERCENTILE(A1:A20, 0.9)"],
    "PERCENTILE.EXC": [
        "array, k",
        "Returns the k-th percentile, k exclusive of 0 and 1.",
        "=PERCENTILE.EXC(A1:A20, 0.9)",
    ],
    "PERCENTILE.INC": [
        "array, k",
        "Returns the k-th percentile, k from 0 to 1 inclusive.",
        "=PERCENTILE.INC(A1:A20, 0.9)",
    ],
    PERCENTRANK: [
        "array, x, [significance]",
        "Returns the rank of a value as a percentage of the data set.",
        "=PERCENTRANK(A1:A20, 8)",
        { significance: "The number of significant digits (default 3)." },
    ],
    "PERCENTRANK.EXC": [
        "array, x, [significance]",
        "Returns the percentage rank, exclusive of 0 and 1.",
        "=PERCENTRANK.EXC(A1:A20, 8)",
        { significance: "The number of significant digits (default 3)." },
    ],
    "PERCENTRANK.INC": [
        "array, x, [significance]",
        "Returns the percentage rank, from 0 to 1 inclusive.",
        "=PERCENTRANK.INC(A1:A20, 8)",
        { significance: "The number of significant digits (default 3)." },
    ],
    PERMUT: ["number, number_chosen", "Returns the number of permutations.", "=PERMUT(10, 3)"],
    PERMUTATIONA: ["number, number_chosen", "Returns permutations with repetitions.", "=PERMUTATIONA(3, 2)"],
    PHI: ["x", "Returns the standard normal density.", "=PHI(0.75)"],
    "POISSON.DIST": ["x, mean, cumulative", "Returns the Poisson distribution.", "=POISSON.DIST(2, 5, TRUE)"],
    PROB: [
        "x_range, prob_range, lower_limit, [upper_limit]",
        "Returns the probability that values are between two limits.",
        "=PROB(A2:A5, B2:B5, 1, 3)",
        { x_range: "The values.", prob_range: "Their probabilities." },
    ],
    QUARTILE: ["array, quart", "Returns a quartile of a data set.", "=QUARTILE(A1:A20, 1)"],
    "QUARTILE.EXC": [
        "array, quart",
        "Returns a quartile, exclusive of the median method.",
        "=QUARTILE.EXC(A1:A20, 1)",
    ],
    "QUARTILE.INC": ["array, quart", "Returns a quartile of a data set.", "=QUARTILE.INC(A1:A20, 1)"],
    RANK: [
        "number, ref, [order]",
        "Returns the rank of a number in a list.",
        "=RANK(B2, B$2:B$20)",
        { ref: "The list of numbers." },
    ],
    "RANK.AVG": [
        "number, ref, [order]",
        "Returns the rank; ties get their average rank.",
        "=RANK.AVG(B2, B$2:B$20)",
        { ref: "The list of numbers." },
    ],
    "RANK.EQ": [
        "number, ref, [order]",
        "Returns the rank; ties share the top rank.",
        "=RANK.EQ(B2, B$2:B$20)",
        { ref: "The list of numbers." },
    ],
    RSQ: [
        "known_ys, known_xs",
        "Returns the square of the Pearson correlation coefficient.",
        "=RSQ(B2:B10, A2:A10)",
    ],
    SKEW: ["number1, [number2], …", "Returns the skewness of a sample.", "=SKEW(A1:A20)"],
    "SKEW.P": ["number1, [number2], …", "Returns the skewness of a population.", "=SKEW.P(A1:A20)"],
    SLOPE: [
        "known_ys, known_xs",
        "Returns the slope of the linear regression line.",
        "=SLOPE(B2:B10, A2:A10)",
    ],
    SMALL: ["array, k", "Returns the k-th smallest value.", "=SMALL(A1:A20, 2)"],
    STANDARDIZE: [
        "x, mean, standard_dev",
        "Returns a normalized value (z-score).",
        "=STANDARDIZE(42, 40, 1.5)",
    ],
    STDEV: ["number1, [number2], …", "Estimates the standard deviation of a sample.", "=STDEV(A1:A20)"],
    "STDEV.P": [
        "number1, [number2], …",
        "Returns the standard deviation of a population.",
        "=STDEV.P(A1:A20)",
    ],
    "STDEV.S": ["number1, [number2], …", "Estimates the standard deviation of a sample.", "=STDEV.S(A1:A20)"],
    STDEVA: [
        "value1, [value2], …",
        "Estimates the sample standard deviation, counting text and logicals.",
        "=STDEVA(A1:A20)",
    ],
    STDEVP: ["number1, [number2], …", "Returns the standard deviation of a population.", "=STDEVP(A1:A20)"],
    STDEVPA: [
        "value1, [value2], …",
        "Returns the population standard deviation, counting text and logicals.",
        "=STDEVPA(A1:A20)",
    ],
    STEYX: [
        "known_ys, known_xs",
        "Returns the standard error of the predicted y values.",
        "=STEYX(B2:B10, A2:A10)",
    ],
    "T.DIST": [
        "x, deg_freedom, cumulative",
        "Returns Student's left-tailed t distribution.",
        "=T.DIST(60, 1, TRUE)",
    ],
    "T.DIST.2T": ["x, deg_freedom", "Returns Student's two-tailed t distribution.", "=T.DIST.2T(1.96, 60)"],
    "T.DIST.RT": ["x, deg_freedom", "Returns Student's right-tailed t distribution.", "=T.DIST.RT(1.96, 60)"],
    "T.INV": [
        "probability, deg_freedom",
        "Returns the left-tailed inverse of Student's t.",
        "=T.INV(0.75, 2)",
    ],
    "T.INV.2T": [
        "probability, deg_freedom",
        "Returns the two-tailed inverse of Student's t.",
        "=T.INV.2T(0.05, 60)",
    ],
    "T.TEST": [
        "array1, array2, tails, type",
        "Returns the probability from Student's t-test.",
        "=T.TEST(A2:A10, B2:B10, 2, 1)",
        { type: "1 paired, 2 equal variance, 3 unequal variance." },
    ],
    TREND: [
        "known_ys, [known_xs], [new_xs], [const]",
        "Returns values along a linear trend.",
        "=TREND(B2:B10, A2:A10, A11:A12)",
    ],
    TRIMMEAN: ["array, percent", "Returns the mean of the interior of a data set.", "=TRIMMEAN(A1:A20, 0.2)"],
    VAR: ["number1, [number2], …", "Estimates the variance of a sample.", "=VAR(A1:A20)"],
    "VAR.P": ["number1, [number2], …", "Returns the variance of a population.", "=VAR.P(A1:A20)"],
    "VAR.S": ["number1, [number2], …", "Estimates the variance of a sample.", "=VAR.S(A1:A20)"],
    VARA: [
        "value1, [value2], …",
        "Estimates the sample variance, counting text and logicals.",
        "=VARA(A1:A20)",
    ],
    VARP: ["number1, [number2], …", "Returns the variance of a population.", "=VARP(A1:A20)"],
    VARPA: [
        "value1, [value2], …",
        "Returns the population variance, counting text and logicals.",
        "=VARPA(A1:A20)",
    ],
    "WEIBULL.DIST": [
        "x, alpha, beta, cumulative",
        "Returns the Weibull distribution.",
        "=WEIBULL.DIST(105, 20, 100, TRUE)",
        { alpha: "The shape parameter.", beta: "The scale parameter." },
    ],
    "Z.TEST": [
        "array, x, [sigma]",
        "Returns the one-tailed p-value of a z-test.",
        "=Z.TEST(A2:A11, 4)",
        { sigma: "The population standard deviation (default: the sample's)." },
    ],
    // Compatibility names kept by Excel for older workbooks.
    BETADIST: [
        "x, alpha, beta, [A], [B]",
        "Older version of BETA.DIST (cumulative).",
        "=BETADIST(0.4, 2, 3)",
    ],
    BETAINV: ["probability, alpha, beta, [A], [B]", "Older version of BETA.INV.", "=BETAINV(0.5, 2, 3)"],
    BINOMDIST: [
        "number_s, trials, probability_s, cumulative",
        "Older version of BINOM.DIST.",
        "=BINOMDIST(6, 10, 0.5, FALSE)",
    ],
    CHIDIST: ["x, deg_freedom", "Older version of CHISQ.DIST.RT.", "=CHIDIST(3, 4)"],
    CHIINV: ["probability, deg_freedom", "Older version of CHISQ.INV.RT.", "=CHIINV(0.05, 3)"],
    CHITEST: ["actual_range, expected_range", "Older version of CHISQ.TEST.", "=CHITEST(B2:C4, E2:F4)"],
    CONFIDENCE: [
        "alpha, standard_dev, size",
        "Older version of CONFIDENCE.NORM.",
        "=CONFIDENCE(0.05, 2.5, 50)",
    ],
    COVAR: ["array1, array2", "Older version of COVARIANCE.P.", "=COVAR(A2:A10, B2:B10)"],
    CRITBINOM: ["trials, probability_s, alpha", "Older version of BINOM.INV.", "=CRITBINOM(6, 0.5, 0.75)"],
    EXPONDIST: ["x, lambda, cumulative", "Older version of EXPON.DIST.", "=EXPONDIST(0.2, 10, TRUE)"],
    FDIST: ["x, deg_freedom1, deg_freedom2", "Older version of F.DIST.RT.", "=FDIST(15, 6, 4)"],
    FINV: ["probability, deg_freedom1, deg_freedom2", "Older version of F.INV.RT.", "=FINV(0.01, 6, 4)"],
    FTEST: ["array1, array2", "Older version of F.TEST.", "=FTEST(A2:A10, B2:B10)"],
    GAMMADIST: ["x, alpha, beta, cumulative", "Older version of GAMMA.DIST.", "=GAMMADIST(10, 9, 2, FALSE)"],
    GAMMAINV: ["probability, alpha, beta", "Older version of GAMMA.INV.", "=GAMMAINV(0.07, 9, 2)"],
    HYPGEOMDIST: [
        "sample_s, number_sample, population_s, number_pop",
        "Older version of HYPGEOM.DIST.",
        "=HYPGEOMDIST(1, 4, 8, 20)",
    ],
    LOGINV: ["probability, mean, standard_dev", "Older version of LOGNORM.INV.", "=LOGINV(0.039, 3.5, 1.2)"],
    LOGNORMDIST: [
        "x, mean, standard_dev",
        "Older version of LOGNORM.DIST (cumulative).",
        "=LOGNORMDIST(4, 3.5, 1.2)",
    ],
    NEGBINOMDIST: [
        "number_f, number_s, probability_s",
        "Older version of NEGBINOM.DIST.",
        "=NEGBINOMDIST(10, 5, 0.25)",
    ],
    NORMDIST: [
        "x, mean, standard_dev, cumulative",
        "Older version of NORM.DIST.",
        "=NORMDIST(42, 40, 1.5, TRUE)",
    ],
    NORMINV: ["probability, mean, standard_dev", "Older version of NORM.INV.", "=NORMINV(0.908, 40, 1.5)"],
    NORMSDIST: ["z", "Older version of NORM.S.DIST (cumulative).", "=NORMSDIST(1.33)"],
    NORMSINV: ["probability", "Older version of NORM.S.INV.", "=NORMSINV(0.908)"],
    POISSON: ["x, mean, cumulative", "Older version of POISSON.DIST.", "=POISSON(2, 5, TRUE)"],
    TDIST: ["x, deg_freedom, tails", "Older version of T.DIST.2T / T.DIST.RT.", "=TDIST(1.96, 60, 2)"],
    TINV: ["probability, deg_freedom", "Older version of T.INV.2T.", "=TINV(0.05, 60)"],
    TTEST: ["array1, array2, tails, type", "Older version of T.TEST.", "=TTEST(A2:A10, B2:B10, 2, 1)"],
    WEIBULL: ["x, alpha, beta, cumulative", "Older version of WEIBULL.DIST.", "=WEIBULL(105, 20, 100, TRUE)"],
    ZTEST: ["array, x, [sigma]", "Older version of Z.TEST.", "=ZTEST(A2:A11, 4)"],
};

const LOGICAL: Record<string, Row> = {
    AND: ["logical1, [logical2], …", "Returns TRUE when every argument is TRUE.", "=AND(A1>0, A1<10)"],
    BYCOL: [
        "array, lambda",
        "Applies a LAMBDA to each column and returns the results.",
        "=BYCOL(A1:C5, LAMBDA(c, SUM(c)))",
    ],
    BYROW: [
        "array, lambda",
        "Applies a LAMBDA to each row and returns the results.",
        "=BYROW(A1:C5, LAMBDA(r, MAX(r)))",
    ],
    FALSE: ["", "Returns the logical value FALSE.", "=FALSE()"],
    IF: [
        "logical_test, value_if_true, [value_if_false]",
        "Returns one value when a condition is TRUE and another when it is FALSE.",
        '=IF(A1>=50, "Pass", "Fail")',
    ],
    IFERROR: ["value, value_if_error", "Returns a fallback when a value is an error.", "=IFERROR(A1/B1, 0)"],
    IFNA: [
        "value, value_if_na",
        "Returns a fallback when a value is #N/A.",
        '=IFNA(VLOOKUP(D2, A:B, 2, FALSE), "Missing")',
    ],
    IFS: [
        "logical_test1, value_if_true1, …",
        "Returns the value for the first TRUE condition.",
        '=IFS(A1>=90, "A", A1>=80, "B", TRUE, "C")',
    ],
    LAMBDA: [
        "[parameter1, …], calculation",
        "Creates a reusable function from parameters and a calculation.",
        "=LAMBDA(x, x*2)(A1)",
        { parameter: "A name for a value passed to the function." },
    ],
    LET: [
        "name1, name_value1, calculation_or_name2, …",
        "Names intermediate results so a formula computes them once.",
        "=LET(x, A1*2, x+x^2)",
        { calculation_or_name: "Another name, or the final calculation that uses the names." },
    ],
    MAKEARRAY: [
        "rows, columns, lambda",
        "Builds an array by calling a LAMBDA with each row and column number.",
        "=MAKEARRAY(3, 3, LAMBDA(r, c, r*c))",
    ],
    MAP: [
        "array1, [array2], …, lambda",
        "Applies a LAMBDA to each value of the arrays.",
        "=MAP(A1:A5, LAMBDA(v, v^2))",
    ],
    NOT: ["logical", "Reverses TRUE and FALSE.", "=NOT(A1>5)"],
    OR: ["logical1, [logical2], …", "Returns TRUE when any argument is TRUE.", '=OR(A1="Yes", B1="Yes")'],
    REDUCE: [
        "[initial_value], array, lambda",
        "Reduces an array to one value by applying a LAMBDA to an accumulator and each value.",
        "=REDUCE(0, A1:A5, LAMBDA(acc, v, acc+v))",
        { initial_value: "The accumulator's starting value." },
    ],
    SCAN: [
        "[initial_value], array, lambda",
        "Like REDUCE, but returns every intermediate accumulator value.",
        "=SCAN(0, A1:A5, LAMBDA(acc, v, acc+v))",
        { initial_value: "The accumulator's starting value." },
    ],
    SWITCH: [
        "expression, value1, result1, [default_or_value2], …",
        "Compares an expression with a list of values and returns the first match's result.",
        '=SWITCH(A1, 1, "One", 2, "Two", "Other")',
        {
            result: "Returned when the expression equals the value before it.",
            default_or_value: "A final default, or another value to compare.",
        },
    ],
    TRUE: ["", "Returns the logical value TRUE.", "=TRUE()"],
    XOR: [
        "logical1, [logical2], …",
        "Returns TRUE when an odd number of arguments are TRUE.",
        "=XOR(A1>0, B1>0)",
    ],
};

const TEXT: Record<string, Row> = {
    ARRAYTOTEXT: [
        "array, [format]",
        "Returns an array's values as text.",
        "=ARRAYTOTEXT(A1:B3)",
        { format: "0 concise (default), 1 strict, quoted and with braces." },
    ],
    CHAR: ["number", "Returns the character for a code number.", "=CHAR(65)"],
    CLEAN: ["text", "Removes nonprinting characters.", "=CLEAN(A1)"],
    CODE: ["text", "Returns the code of the first character.", '=CODE("A")'],
    CONCAT: ["text1, [text2], …", "Joins text and ranges.", '=CONCAT(A1, " ", B1)'],
    CONCATENATE: ["text1, [text2], …", "Joins text values.", '=CONCATENATE(A1, " ", B1)'],
    DOLLAR: ["number, [decimals]", "Formats a number as currency text.", "=DOLLAR(1234.567, 2)"],
    ENCODEURL: ["text", "Returns a URL-encoded string.", '=ENCODEURL("a b&c")'],
    EXACT: ["text1, text2", "Compares two texts, including letter case.", "=EXACT(A1, B1)"],
    FIND: [
        "find_text, within_text, [start_num]",
        "Finds text, case-sensitively; returns its position.",
        '=FIND("-", A1)',
    ],
    FIXED: [
        "number, [decimals], [no_commas]",
        "Formats a number as text with fixed decimals.",
        "=FIXED(1234.567, 1)",
        { no_commas: "TRUE to omit thousands separators." },
    ],
    JOIN: [
        "delimiter, value_or_array1, [value_or_array2], …",
        "Joins values and arrays with a delimiter.",
        '=JOIN(", ", A1:A5)',
    ],
    LEFT: ["text, [num_chars]", "Returns characters from the start of text.", "=LEFT(A1, 3)"],
    LEN: ["text", "Returns the number of characters.", "=LEN(A1)"],
    LOWER: ["text", "Converts text to lowercase.", "=LOWER(A1)"],
    MID: ["text, start_num, num_chars", "Returns characters from the middle of text.", "=MID(A1, 2, 3)"],
    NUMBERVALUE: [
        "text, [decimal_separator], [group_separator]",
        "Converts text to a number with the given separators.",
        '=NUMBERVALUE("1.234,5", ",", ".")',
        { decimal_separator: "The decimal separator.", group_separator: "The thousands separator." },
    ],
    PROPER: ["text", "Capitalizes the first letter of each word.", "=PROPER(A1)"],
    REGEXEXTRACT: [
        "text, pattern, [return_mode], [case_sensitivity]",
        "Extracts the text that matches a regular expression.",
        '=REGEXEXTRACT(A1, "[0-9]+")',
        {
            pattern: "The regular expression.",
            return_mode: "0 first match, 1 all matches, 2 capture groups.",
            case_sensitivity: "0 case-sensitive (default), 1 ignore case.",
        },
    ],
    REGEXMATCH: [
        "text, regular_expression",
        "Tests whether text matches a regular expression.",
        '=REGEXMATCH(A1, "^[0-9]+$")',
        { regular_expression: "The pattern to match." },
    ],
    REGEXREPLACE: [
        "text, pattern, replacement, [occurrence], [case_sensitivity]",
        "Replaces text that matches a regular expression.",
        '=REGEXREPLACE(A1, "\\s+", " ")',
        {
            pattern: "The regular expression.",
            replacement: "The replacement text.",
            occurrence: "Which match to replace (default: all).",
        },
    ],
    REGEXTEST: [
        "text, pattern, [case_sensitivity]",
        "Tests whether text matches a regular expression.",
        '=REGEXTEST(A1, "^[A-Z]{3}$")',
        { pattern: "The regular expression." },
    ],
    REPLACE: [
        "old_text, start_num, num_chars, new_text",
        "Replaces characters at a position.",
        '=REPLACE(A1, 1, 3, "XYZ")',
    ],
    REPT: [
        "text, number_times",
        "Repeats text a number of times.",
        '=REPT("*", 5)',
        { number_times: "How many times." },
    ],
    RIGHT: ["text, [num_chars]", "Returns characters from the end of text.", "=RIGHT(A1, 4)"],
    SEARCH: [
        "find_text, within_text, [start_num]",
        "Finds text ignoring case (wildcards allowed); returns its position.",
        '=SEARCH("total", A1)',
    ],
    SPLIT: [
        "text, delimiter, [split_by_each], [remove_empty_text]",
        "Splits text around a delimiter into neighbouring cells.",
        '=SPLIT(A1, ",")',
        {
            split_by_each: "TRUE (default) splits at each character of the delimiter.",
            remove_empty_text: "TRUE (default) drops empty parts.",
        },
    ],
    SUBSTITUTE: [
        "text, old_text, new_text, [instance_num]",
        "Replaces existing text with new text.",
        '=SUBSTITUTE(A1, "-", "/")',
    ],
    T: ["value", "Returns the value if it is text, otherwise empty text.", "=T(A1)"],
    TEXT: ["value, format_text", "Formats a value as text with a number format.", '=TEXT(A1, "yyyy-mm-dd")'],
    TEXTAFTER: [
        "text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found]",
        "Returns the text after a delimiter.",
        '=TEXTAFTER(A1, "@")',
        {
            match_mode: "0 case-sensitive (default), 1 ignore case.",
            match_end: "1 treats the end of text as a delimiter.",
        },
    ],
    TEXTBEFORE: [
        "text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found]",
        "Returns the text before a delimiter.",
        '=TEXTBEFORE(A1, "@")',
        {
            match_mode: "0 case-sensitive (default), 1 ignore case.",
            match_end: "1 treats the end of text as a delimiter.",
        },
    ],
    TEXTJOIN: [
        "delimiter, ignore_empty, text1, …",
        "Joins text with a delimiter, optionally skipping empty cells.",
        '=TEXTJOIN(", ", TRUE, A1:A5)',
    ],
    TEXTSPLIT: [
        "text, col_delimiter, [row_delimiter], [ignore_empty], [match_mode], [pad_with]",
        "Splits text into columns and rows by delimiters.",
        '=TEXTSPLIT(A1, ",")',
        { col_delimiter: "Splits text across columns.", row_delimiter: "Splits text down rows." },
    ],
    TRIM: ["text", "Removes leading, trailing and repeated spaces.", "=TRIM(A1)"],
    UNICHAR: ["number", "Returns the Unicode character for a code point.", "=UNICHAR(9731)"],
    UNICODE: ["text", "Returns the code point of the first character.", '=UNICODE("☃")'],
    UPPER: ["text", "Converts text to uppercase.", "=UPPER(A1)"],
    VALUE: ["text", "Converts text that looks like a number into a number.", '=VALUE("12.5%")'],
    VALUETOTEXT: [
        "value, [format]",
        "Returns a value as text.",
        "=VALUETOTEXT(A1)",
        { format: "0 concise (default), 1 strict, quoted." },
    ],
};

const DATE_TIME: Record<string, Row> = {
    DATE: ["year, month, day", "Returns the serial number of a date.", "=DATE(2024, 3, 15)"],
    DATEDIF: [
        "start_date, end_date, unit",
        "Returns the years, months or days between two dates.",
        '=DATEDIF(A1, TODAY(), "Y")',
    ],
    DATEVALUE: ["date_text", "Converts date text to a serial number.", '=DATEVALUE("2024-03-15")'],
    DAY: ["serial_number", "Returns the day of the month, 1 to 31.", "=DAY(A1)"],
    DAYS: ["end_date, start_date", "Returns the number of days between two dates.", "=DAYS(B1, A1)"],
    DAYS360: [
        "start_date, end_date, [method]",
        "Returns the days between two dates on a 360-day year.",
        "=DAYS360(A1, B1)",
        { method: "FALSE US (NASD, default), TRUE European." },
    ],
    EDATE: ["start_date, months", "Returns the date a number of months away.", "=EDATE(A1, 3)"],
    EOMONTH: [
        "start_date, months",
        "Returns the last day of the month a number of months away.",
        "=EOMONTH(A1, 0)",
    ],
    HOUR: ["serial_number", "Returns the hour, 0 to 23.", "=HOUR(A1)"],
    ISOWEEKNUM: ["date", "Returns the ISO week number of the year.", "=ISOWEEKNUM(A1)"],
    MINUTE: ["serial_number", "Returns the minute, 0 to 59.", "=MINUTE(A1)"],
    MONTH: ["serial_number", "Returns the month, 1 to 12.", "=MONTH(A1)"],
    NETWORKDAYS: [
        "start_date, end_date, [holidays]",
        "Returns the number of working days between two dates.",
        "=NETWORKDAYS(A1, B1, H1:H10)",
    ],
    "NETWORKDAYS.INTL": [
        "start_date, end_date, [weekend], [holidays]",
        "Returns working days between two dates with custom weekends.",
        "=NETWORKDAYS.INTL(A1, B1, 11)",
    ],
    NOW: ["", "Returns the current date and time.", "=NOW()"],
    SECOND: ["serial_number", "Returns the second, 0 to 59.", "=SECOND(A1)"],
    TIME: ["hour, minute, second", "Returns a time as a fraction of a day.", "=TIME(14, 30, 0)"],
    TIMEVALUE: ["time_text", "Converts time text to a fraction of a day.", '=TIMEVALUE("6:45 PM")'],
    TODAY: ["", "Returns today's date.", "=TODAY()"],
    WEEKDAY: [
        "serial_number, [return_type]",
        "Returns the day of the week (1 Sunday … 7 Saturday by default).",
        "=WEEKDAY(A1, 2)",
        { return_type: "1 Sun=1 (default), 2 Mon=1, 3 Mon=0, 11–17 other starts." },
    ],
    WEEKNUM: [
        "serial_number, [return_type]",
        "Returns the week number of the year.",
        "=WEEKNUM(A1)",
        { return_type: "1 weeks start Sunday (default), 2 Monday, 21 ISO." },
    ],
    WORKDAY: [
        "start_date, days, [holidays]",
        "Returns the date a number of working days away.",
        "=WORKDAY(A1, 10)",
    ],
    "WORKDAY.INTL": [
        "start_date, days, [weekend], [holidays]",
        "Returns the date a number of working days away, with custom weekends.",
        "=WORKDAY.INTL(A1, 10, 7)",
    ],
    YEAR: ["serial_number", "Returns the year.", "=YEAR(A1)"],
    YEARFRAC: [
        "start_date, end_date, [basis]",
        "Returns the fraction of a year between two dates.",
        "=YEARFRAC(A1, B1)",
    ],
};

const LOOKUP: Record<string, Row> = {
    ADDRESS: [
        "row_num, column_num, [abs_num], [a1], [sheet_text]",
        "Returns a cell address as text.",
        "=ADDRESS(2, 3)",
        { abs_num: "1 $A$1 (default), 2 A$1, 3 $A1, 4 A1.", sheet_text: "A sheet name to prefix." },
    ],
    AREAS: ["reference", "Returns the number of areas in a reference.", "=AREAS((A1:B2, D1:D5))"],
    CHOOSE: [
        "index_num, value1, [value2], …",
        "Returns the value at a 1-based position in a list.",
        '=CHOOSE(2, "Low", "Mid", "High")',
    ],
    CHOOSECOLS: [
        "array, col_num1, [col_num2], …",
        "Returns the chosen columns of an array.",
        "=CHOOSECOLS(A1:D10, 1, 3)",
    ],
    CHOOSEROWS: [
        "array, row_num1, [row_num2], …",
        "Returns the chosen rows of an array.",
        "=CHOOSEROWS(A1:D10, 1, -1)",
    ],
    COLUMN: ["[reference]", "Returns the column number of a reference.", "=COLUMN(C5)"],
    COLUMNS: ["array", "Returns the number of columns in a reference or array.", "=COLUMNS(A1:D1)"],
    DROP: [
        "array, rows, [columns]",
        "Removes rows or columns from the start (positive) or end (negative).",
        "=DROP(A1:D10, 1)",
    ],
    EXPAND: [
        "array, rows, [columns], [pad_with]",
        "Expands an array to the given size.",
        "=EXPAND(A1:B2, 3, 3, 0)",
    ],
    FILTER: [
        "array, include, [if_empty]",
        "Returns the rows (or columns) that meet a condition.",
        '=FILTER(A2:C20, B2:B20>100, "None")',
    ],
    FLATTEN: ["range1, [range2], …", "Returns the values of ranges as one column.", "=FLATTEN(A1:C3)"],
    FORMULATEXT: ["reference", "Returns the formula of a cell as text.", "=FORMULATEXT(C2)"],
    HLOOKUP: [
        "lookup_value, table_array, row_index_num, [range_lookup]",
        "Looks across the first row of a table and returns a value from a lower row.",
        '=HLOOKUP("Q2", A1:E5, 3, FALSE)',
    ],
    HSTACK: ["array1, [array2], …", "Joins arrays side by side.", "=HSTACK(A1:A5, C1:C5)"],
    HYPERLINK: [
        "link_location, [friendly_name]",
        "Creates a clickable link.",
        '=HYPERLINK("https://example.com", "Example")',
        { link_location: "The URL or location.", friendly_name: "The text shown in the cell." },
    ],
    INDEX: [
        "array, row_num, [column_num]",
        "Returns the value at a row and column of a range.",
        "=INDEX(A1:C10, 3, 2)",
    ],
    INDIRECT: ["ref_text, [a1]", "Returns the reference named by a text string.", '=INDIRECT("B" & D1)'],
    LOOKUP: [
        "lookup_value, lookup_vector, [result_vector]",
        "Looks up a value in a sorted row or column.",
        "=LOOKUP(4.2, A2:A10, B2:B10)",
    ],
    MATCH: [
        "lookup_value, lookup_array, [match_type]",
        "Returns the relative position of a value.",
        '=MATCH("Pears", A2:A10, 0)',
    ],
    OFFSET: [
        "reference, rows, cols, [height], [width]",
        "Returns a reference shifted from a starting cell.",
        "=SUM(OFFSET(A1, 1, 0, 5, 1))",
        { rows: "Rows to move down (negative: up).", cols: "Columns to move right (negative: left)." },
    ],
    ROW: ["[reference]", "Returns the row number of a reference.", "=ROW(C5)"],
    ROWS: ["array", "Returns the number of rows in a reference or array.", "=ROWS(A1:A10)"],
    SORT: [
        "array, [sort_index], [sort_order], [by_col]",
        "Sorts the contents of a range or array.",
        "=SORT(A2:B20, 2, -1)",
    ],
    SORTBY: [
        "array, by_array1, [sort_order1], …",
        "Sorts a range by the values of other ranges.",
        "=SORTBY(A2:A20, B2:B20, -1)",
    ],
    TAKE: [
        "array, rows, [columns]",
        "Returns rows or columns from the start (positive) or end (negative).",
        "=TAKE(A1:D10, 3)",
    ],
    TOCOL: [
        "array, [ignore], [scan_by_column]",
        "Returns an array as a single column.",
        "=TOCOL(A1:C3)",
        {
            ignore: "0 keep all, 1 skip blanks, 2 skip errors, 3 both.",
            scan_by_column: "TRUE to read column by column.",
        },
    ],
    TOROW: [
        "array, [ignore], [scan_by_column]",
        "Returns an array as a single row.",
        "=TOROW(A1:C3)",
        {
            ignore: "0 keep all, 1 skip blanks, 2 skip errors, 3 both.",
            scan_by_column: "TRUE to read column by column.",
        },
    ],
    TRANSPOSE: ["array", "Swaps the rows and columns of an array.", "=TRANSPOSE(A1:C2)"],
    UNIQUE: ["array, [by_col], [exactly_once]", "Returns the unique values of a range.", "=UNIQUE(A2:A50)"],
    VLOOKUP: [
        "lookup_value, table_array, col_index_num, [range_lookup]",
        "Looks down the first column of a table and returns a value from another column.",
        "=VLOOKUP(D2, A2:B20, 2, FALSE)",
    ],
    VSTACK: ["array1, [array2], …", "Stacks arrays on top of each other.", "=VSTACK(A1:B3, A10:B12)"],
    WRAPCOLS: [
        "vector, wrap_count, [pad_with]",
        "Wraps a row or column into columns.",
        "=WRAPCOLS(A1:A12, 4)",
        { vector: "The row or column to wrap." },
    ],
    WRAPROWS: [
        "vector, wrap_count, [pad_with]",
        "Wraps a row or column into rows.",
        "=WRAPROWS(A1:A12, 4)",
        { vector: "The row or column to wrap." },
    ],
    XLOOKUP: [
        "lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]",
        "Looks up a value and returns the matching item from another range.",
        '=XLOOKUP(D2, A2:A20, B2:B20, "Not found")',
    ],
    XMATCH: [
        "lookup_value, lookup_array, [match_mode], [search_mode]",
        "Returns the relative position of a value; exact match by default.",
        '=XMATCH("Pears", A2:A10)',
    ],
};

const FINANCIAL: Record<string, Row> = {
    ACCRINT: [
        "issue, first_interest, settlement, rate, par, frequency, [basis], [calc_method]",
        "Returns the accrued interest of a security that pays periodic interest.",
        "=ACCRINT(A1, A2, A3, 10%, 1000, 2)",
        {
            first_interest: "The first interest date.",
            rate: "The annual coupon rate.",
            calc_method: "TRUE accrues from issue (default).",
        },
    ],
    ACCRINTM: [
        "issue, settlement, rate, par, [basis]",
        "Returns the accrued interest of a security that pays at maturity.",
        "=ACCRINTM(A1, A2, 10%, 1000)",
        { rate: "The annual coupon rate." },
    ],
    COUPDAYBS: [
        "settlement, maturity, frequency, [basis]",
        "Days from the coupon period's start to settlement.",
        "=COUPDAYBS(A1, A2, 2)",
    ],
    COUPDAYS: [
        "settlement, maturity, frequency, [basis]",
        "Days in the coupon period that contains settlement.",
        "=COUPDAYS(A1, A2, 2)",
    ],
    COUPDAYSNC: [
        "settlement, maturity, frequency, [basis]",
        "Days from settlement to the next coupon date.",
        "=COUPDAYSNC(A1, A2, 2)",
    ],
    COUPNCD: [
        "settlement, maturity, frequency, [basis]",
        "Returns the next coupon date after settlement.",
        "=COUPNCD(A1, A2, 2)",
    ],
    COUPNUM: [
        "settlement, maturity, frequency, [basis]",
        "Returns the number of coupons payable.",
        "=COUPNUM(A1, A2, 2)",
    ],
    COUPPCD: [
        "settlement, maturity, frequency, [basis]",
        "Returns the previous coupon date before settlement.",
        "=COUPPCD(A1, A2, 2)",
    ],
    CUMIPMT: [
        "rate, nper, pv, start_period, end_period, type",
        "Returns the cumulative interest paid between two periods.",
        "=CUMIPMT(5%/12, 360, 200000, 1, 12, 0)",
    ],
    CUMPRINC: [
        "rate, nper, pv, start_period, end_period, type",
        "Returns the cumulative principal paid between two periods.",
        "=CUMPRINC(5%/12, 360, 200000, 1, 12, 0)",
    ],
    DB: [
        "cost, salvage, life, period, [month]",
        "Returns depreciation by the fixed-declining balance method.",
        "=DB(10000, 1000, 5, 1)",
        { month: "Months in the first year (default 12)." },
    ],
    DDB: [
        "cost, salvage, life, period, [factor]",
        "Returns depreciation by the double-declining balance method.",
        "=DDB(10000, 1000, 5, 1)",
    ],
    DISC: [
        "settlement, maturity, pr, redemption, [basis]",
        "Returns the discount rate of a security.",
        "=DISC(A1, A2, 97.975, 100)",
    ],
    DOLLARDE: [
        "fractional_dollar, fraction",
        "Converts a fractional dollar price to a decimal.",
        "=DOLLARDE(1.02, 16)",
        { fractional_dollar: "The price as integer.fraction.", fraction: "The denominator of the fraction." },
    ],
    DOLLARFR: [
        "decimal_dollar, fraction",
        "Converts a decimal dollar price to a fractional one.",
        "=DOLLARFR(1.125, 16)",
        { decimal_dollar: "The decimal price.", fraction: "The denominator of the fraction." },
    ],
    DURATION: [
        "settlement, maturity, coupon, yld, frequency, [basis]",
        "Returns the Macaulay duration of a security.",
        "=DURATION(A1, A2, 8%, 9%, 2)",
        { coupon: "The annual coupon rate." },
    ],
    EFFECT: [
        "nominal_rate, npery",
        "Returns the effective annual interest rate.",
        "=EFFECT(5.25%, 4)",
        { nominal_rate: "The nominal annual rate." },
    ],
    FV: [
        "rate, nper, pmt, [pv], [type]",
        "Returns the future value of an investment.",
        "=FV(6%/12, 120, -200)",
    ],
    FVSCHEDULE: [
        "principal, schedule",
        "Returns a future value after a series of interest rates.",
        "=FVSCHEDULE(1000, {0.09, 0.11, 0.1})",
    ],
    INTRATE: [
        "settlement, maturity, investment, redemption, [basis]",
        "Returns the interest rate of a fully invested security.",
        "=INTRATE(A1, A2, 1000000, 1014420)",
        { redemption: "The amount received at maturity." },
    ],
    IPMT: [
        "rate, per, nper, pv, [fv], [type]",
        "Returns the interest part of a payment.",
        "=IPMT(5%/12, 1, 360, 200000)",
    ],
    IRR: ["values, [guess]", "Returns the internal rate of return of cash flows.", "=IRR(B2:B8)"],
    ISPMT: [
        "rate, per, nper, pv",
        "Returns the interest paid in a period of a straight-line loan.",
        "=ISPMT(5%/12, 1, 36, 8000000)",
    ],
    MDURATION: [
        "settlement, maturity, coupon, yld, frequency, [basis]",
        "Returns the modified Macaulay duration of a security.",
        "=MDURATION(A1, A2, 8%, 9%, 2)",
        { coupon: "The annual coupon rate." },
    ],
    MIRR: [
        "values, finance_rate, reinvest_rate",
        "Returns the modified internal rate of return.",
        "=MIRR(B2:B8, 10%, 12%)",
    ],
    NOMINAL: [
        "effect_rate, npery",
        "Returns the nominal annual interest rate.",
        "=NOMINAL(5.3543%, 4)",
        { effect_rate: "The effective rate." },
    ],
    NPER: [
        "rate, pmt, pv, [fv], [type]",
        "Returns the number of periods of an investment.",
        "=NPER(1%, -100, 1000)",
    ],
    NPV: [
        "rate, value1, [value2], …",
        "Returns the net present value of periodic cash flows.",
        "=NPV(10%, B3:B8) + B2",
        { rate: "The discount rate per period.", value: "Cash flows at the end of each period." },
    ],
    PDURATION: [
        "rate, pv, fv",
        "Returns the periods needed to reach a value.",
        "=PDURATION(2.5%, 2000, 2200)",
        { fv: "The desired future value." },
    ],
    PMT: [
        "rate, nper, pv, [fv], [type]",
        "Returns the payment of a loan with constant payments.",
        "=PMT(5%/12, 360, 200000)",
    ],
    PPMT: [
        "rate, per, nper, pv, [fv], [type]",
        "Returns the principal part of a payment.",
        "=PPMT(5%/12, 1, 360, 200000)",
    ],
    PRICE: [
        "settlement, maturity, rate, yld, redemption, frequency, [basis]",
        "Returns the price per $100 of a security that pays periodic interest.",
        "=PRICE(A1, A2, 5.75%, 6.5%, 100, 2)",
        { rate: "The annual coupon rate." },
    ],
    PRICEDISC: [
        "settlement, maturity, discount, redemption, [basis]",
        "Returns the price per $100 of a discounted security.",
        "=PRICEDISC(A1, A2, 5.25%, 100)",
    ],
    PRICEMAT: [
        "settlement, maturity, issue, rate, yld, [basis]",
        "Returns the price per $100 of a security that pays interest at maturity.",
        "=PRICEMAT(A1, A2, A3, 6.1%, 6.1%)",
        { rate: "The interest rate at issue." },
    ],
    PV: [
        "rate, nper, pmt, [fv], [type]",
        "Returns the present value of an investment.",
        "=PV(8%/12, 240, 500)",
    ],
    RATE: [
        "nper, pmt, pv, [fv], [type], [guess]",
        "Returns the interest rate per period of an annuity.",
        "=RATE(48, -200, 8000)*12",
    ],
    RECEIVED: [
        "settlement, maturity, investment, discount, [basis]",
        "Returns the amount received at maturity of a fully invested security.",
        "=RECEIVED(A1, A2, 1000000, 5.75%)",
    ],
    RRI: ["nper, pv, fv", "Returns the equivalent interest rate for growth.", "=RRI(96, 10000, 11000)"],
    SLN: [
        "cost, salvage, life",
        "Returns straight-line depreciation for one period.",
        "=SLN(30000, 7500, 10)",
    ],
    SYD: [
        "cost, salvage, life, per",
        "Returns sum-of-years' digits depreciation for a period.",
        "=SYD(30000, 7500, 10, 1)",
        { per: "The period." },
    ],
    TBILLEQ: [
        "settlement, maturity, discount",
        "Returns the bond-equivalent yield of a Treasury bill.",
        "=TBILLEQ(A1, A2, 9.14%)",
    ],
    TBILLPRICE: [
        "settlement, maturity, discount",
        "Returns the price per $100 of a Treasury bill.",
        "=TBILLPRICE(A1, A2, 9%)",
    ],
    TBILLYIELD: [
        "settlement, maturity, pr",
        "Returns the yield of a Treasury bill.",
        "=TBILLYIELD(A1, A2, 98.45)",
    ],
    VDB: [
        "cost, salvage, life, start_period, end_period, [factor], [no_switch]",
        "Returns declining-balance depreciation over any span of periods.",
        "=VDB(2400, 300, 10, 0, 1)",
    ],
    XIRR: [
        "values, dates, [guess]",
        "Returns the internal rate of return of irregular cash flows.",
        "=XIRR(B2:B6, A2:A6)",
    ],
    XNPV: [
        "rate, values, dates",
        "Returns the net present value of irregular cash flows.",
        "=XNPV(9%, B2:B6, A2:A6)",
    ],
    YIELD: [
        "settlement, maturity, rate, pr, redemption, frequency, [basis]",
        "Returns the yield of a security that pays periodic interest.",
        "=YIELD(A1, A2, 5.75%, 95.04, 100, 2)",
        { rate: "The annual coupon rate." },
    ],
    YIELDDISC: [
        "settlement, maturity, pr, redemption, [basis]",
        "Returns the annual yield of a discounted security.",
        "=YIELDDISC(A1, A2, 99.795, 100)",
    ],
    YIELDMAT: [
        "settlement, maturity, issue, rate, pr, [basis]",
        "Returns the annual yield of a security that pays interest at maturity.",
        "=YIELDMAT(A1, A2, A3, 6.25%, 100.0123)",
        { rate: "The interest rate at issue." },
    ],
};

const INFORMATION: Record<string, Row> = {
    CELL: [
        "info_type, [reference]",
        "Returns information about a cell's formatting, location or contents.",
        '=CELL("address", B3)',
    ],
    "ERROR.TYPE": ["error_val", "Returns a number for an error type (1 #NULL! … 7 #N/A).", "=ERROR.TYPE(A1)"],
    INFO: [
        "type_text",
        "Returns information about the environment.",
        '=INFO("release")',
        { type_text: 'What to return, e.g. "release".' },
    ],
    ISBLANK: ["value", "Returns TRUE when a cell is empty.", "=ISBLANK(A1)"],
    ISEMAIL: ["value", "Returns TRUE when a value is a valid email address.", "=ISEMAIL(A1)"],
    ISERR: ["value", "Returns TRUE for any error except #N/A.", "=ISERR(A1)"],
    ISERROR: ["value", "Returns TRUE for any error value.", "=ISERROR(A1/B1)"],
    ISEVEN: ["number", "Returns TRUE when a number is even.", "=ISEVEN(A1)"],
    ISFORMULA: ["reference", "Returns TRUE when a cell contains a formula.", "=ISFORMULA(C2)"],
    ISLOGICAL: ["value", "Returns TRUE when a value is TRUE or FALSE.", "=ISLOGICAL(A1)"],
    ISNA: ["value", "Returns TRUE when a value is #N/A.", "=ISNA(MATCH(D2, A:A, 0))"],
    ISNONTEXT: ["value", "Returns TRUE when a value is not text.", "=ISNONTEXT(A1)"],
    ISNUMBER: ["value", "Returns TRUE when a value is a number.", "=ISNUMBER(A1)"],
    ISODD: ["number", "Returns TRUE when a number is odd.", "=ISODD(A1)"],
    ISOMITTED: [
        "argument",
        "Returns TRUE when a LAMBDA argument is missing.",
        "=LAMBDA(x, IF(ISOMITTED(x), 0, x))()",
        { argument: "A LAMBDA parameter." },
    ],
    ISURL: ["value", "Returns TRUE when a value is a valid URL.", "=ISURL(A1)"],
    ISREF: ["value", "Returns TRUE when a value is a reference.", "=ISREF(A1)"],
    ISTEXT: ["value", "Returns TRUE when a value is text.", "=ISTEXT(A1)"],
    N: ["value", "Converts a value to a number (text becomes 0).", "=N(A1)"],
    NA: ["", "Returns the #N/A error value.", "=NA()"],
    SHEET: ["[value]", "Returns the sheet number of a reference or sheet name.", "=SHEET()"],
    SHEETS: [
        "[reference]",
        "Returns the number of sheets in a reference (default: the workbook).",
        "=SHEETS()",
    ],
    TYPE: [
        "value",
        "Returns the type of a value: 1 number, 2 text, 4 logical, 16 error, 64 array.",
        "=TYPE(A1)",
    ],
};

const BASE_ARGS = {
    number: "The number to convert.",
    places: "The minimum number of characters (padded with zeros).",
};
const ENGINEERING: Record<string, Row> = {
    BESSELI: ["x, n", "Returns the modified Bessel function In(x).", "=BESSELI(1.5, 1)"],
    BESSELJ: ["x, n", "Returns the Bessel function Jn(x).", "=BESSELJ(1.9, 2)"],
    BESSELK: ["x, n", "Returns the modified Bessel function Kn(x).", "=BESSELK(1.5, 1)"],
    BESSELY: ["x, n", "Returns the Bessel function Yn(x).", "=BESSELY(2.5, 1)"],
    BIN2DEC: ["number", "Converts a binary number to decimal.", '=BIN2DEC("1100100")', BASE_ARGS],
    BIN2HEX: [
        "number, [places]",
        "Converts a binary number to hexadecimal.",
        '=BIN2HEX("11111011", 4)',
        BASE_ARGS,
    ],
    BIN2OCT: ["number, [places]", "Converts a binary number to octal.", '=BIN2OCT("1001", 3)', BASE_ARGS],
    BITAND: ["number1, number2", "Returns the bitwise AND of two numbers.", "=BITAND(13, 25)"],
    BITLSHIFT: ["number, shift_amount", "Shifts a number's bits left.", "=BITLSHIFT(4, 2)"],
    BITOR: ["number1, number2", "Returns the bitwise OR of two numbers.", "=BITOR(23, 10)"],
    BITRSHIFT: ["number, shift_amount", "Shifts a number's bits right.", "=BITRSHIFT(13, 2)"],
    BITXOR: ["number1, number2", "Returns the bitwise XOR of two numbers.", "=BITXOR(5, 3)"],
    COMPLEX: [
        "real_num, i_num, [suffix]",
        "Builds a complex number from real and imaginary parts.",
        "=COMPLEX(3, 4)",
        { suffix: '"i" (default) or "j".' },
    ],
    CONVERT: [
        "number, from_unit, to_unit",
        "Converts a number between measurement units.",
        '=CONVERT(25.4, "mm", "in")',
    ],
    DEC2BIN: ["number, [places]", "Converts a decimal number to binary.", "=DEC2BIN(9, 4)", BASE_ARGS],
    DEC2HEX: ["number, [places]", "Converts a decimal number to hexadecimal.", "=DEC2HEX(255)", BASE_ARGS],
    DEC2OCT: ["number, [places]", "Converts a decimal number to octal.", "=DEC2OCT(58, 3)", BASE_ARGS],
    DELTA: ["number1, [number2]", "Returns 1 when two numbers are equal, otherwise 0.", "=DELTA(5, 4)"],
    ERF: ["lower_limit, [upper_limit]", "Returns the error function.", "=ERF(0.745)"],
    "ERF.PRECISE": ["x", "Returns the error function from 0 to x.", "=ERF.PRECISE(0.745)"],
    ERFC: ["x", "Returns the complementary error function.", "=ERFC(1)"],
    "ERFC.PRECISE": ["x", "Returns the complementary error function.", "=ERFC.PRECISE(1)"],
    GESTEP: [
        "number, [step]",
        "Returns 1 when a number is at least the step, otherwise 0.",
        "=GESTEP(5, 4)",
        { step: "The threshold (default 0)." },
    ],
    HEX2BIN: ["number, [places]", "Converts a hexadecimal number to binary.", '=HEX2BIN("F", 8)', BASE_ARGS],
    HEX2DEC: ["number", "Converts a hexadecimal number to decimal.", '=HEX2DEC("FF")', BASE_ARGS],
    HEX2OCT: ["number, [places]", "Converts a hexadecimal number to octal.", '=HEX2OCT("F", 3)', BASE_ARGS],
    IMABS: ["inumber", "Returns the absolute value (modulus) of a complex number.", '=IMABS("5+12i")'],
    IMAGINARY: ["inumber", "Returns the imaginary coefficient of a complex number.", '=IMAGINARY("3+4i")'],
    IMARGUMENT: ["inumber", "Returns the argument θ of a complex number, in radians.", '=IMARGUMENT("3+4i")'],
    IMCONJUGATE: ["inumber", "Returns the complex conjugate.", '=IMCONJUGATE("3+4i")'],
    IMCOS: ["inumber", "Returns the cosine of a complex number.", '=IMCOS("1+i")'],
    IMDIV: [
        "inumber1, inumber2",
        "Returns the quotient of two complex numbers.",
        '=IMDIV("-238+240i", "10+24i")',
    ],
    IMEXP: ["inumber", "Returns the exponential of a complex number.", '=IMEXP("1+i")'],
    IMLN: ["inumber", "Returns the natural logarithm of a complex number.", '=IMLN("3+4i")'],
    IMPOWER: ["inumber, number", "Raises a complex number to a power.", '=IMPOWER("2+3i", 3)'],
    IMPRODUCT: [
        "inumber1, [inumber2], …",
        "Returns the product of complex numbers.",
        '=IMPRODUCT("3+4i", "5-3i")',
    ],
    IMREAL: ["inumber", "Returns the real coefficient of a complex number.", '=IMREAL("6-9i")'],
    IMSIN: ["inumber", "Returns the sine of a complex number.", '=IMSIN("4+3i")'],
    IMSQRT: ["inumber", "Returns the square root of a complex number.", '=IMSQRT("1+i")'],
    IMSUB: [
        "inumber1, inumber2",
        "Returns the difference of two complex numbers.",
        '=IMSUB("13+4i", "5+3i")',
    ],
    IMSUM: ["inumber1, [inumber2], …", "Returns the sum of complex numbers.", '=IMSUM("3+4i", "5-3i")'],
    OCT2BIN: ["number, [places]", "Converts an octal number to binary.", '=OCT2BIN("3", 3)', BASE_ARGS],
    OCT2DEC: ["number", "Converts an octal number to decimal.", '=OCT2DEC("54")', BASE_ARGS],
    OCT2HEX: [
        "number, [places]",
        "Converts an octal number to hexadecimal.",
        '=OCT2HEX("100", 4)',
        BASE_ARGS,
    ],
};

const DATABASE_ARGS = "database, field, criteria";
const DATABASE: Record<string, Row> = {
    DAVERAGE: [
        DATABASE_ARGS,
        "Averages a column of the rows that match the criteria.",
        '=DAVERAGE(A1:E20, "Yield", G1:H2)',
    ],
    DCOUNT: [
        DATABASE_ARGS,
        "Counts the numbers in a column of the matching rows.",
        '=DCOUNT(A1:E20, "Age", G1:H2)',
    ],
    DCOUNTA: [
        DATABASE_ARGS,
        "Counts the nonempty cells in a column of the matching rows.",
        '=DCOUNTA(A1:E20, "Name", G1:H2)',
    ],
    DGET: [
        DATABASE_ARGS,
        "Returns the single value in a column of the matching row.",
        '=DGET(A1:E20, "Price", G1:H2)',
    ],
    DMAX: [
        DATABASE_ARGS,
        "Returns the largest value in a column of the matching rows.",
        '=DMAX(A1:E20, "Profit", G1:H2)',
    ],
    DMIN: [
        DATABASE_ARGS,
        "Returns the smallest value in a column of the matching rows.",
        '=DMIN(A1:E20, "Profit", G1:H2)',
    ],
    DPRODUCT: [
        DATABASE_ARGS,
        "Multiplies the values in a column of the matching rows.",
        '=DPRODUCT(A1:E20, "Yield", G1:H2)',
    ],
    DSTDEV: [
        DATABASE_ARGS,
        "Estimates the sample standard deviation of the matching rows.",
        '=DSTDEV(A1:E20, "Yield", G1:H2)',
    ],
    DSTDEVP: [
        DATABASE_ARGS,
        "Returns the population standard deviation of the matching rows.",
        '=DSTDEVP(A1:E20, "Yield", G1:H2)',
    ],
    DSUM: [
        DATABASE_ARGS,
        "Adds the values in a column of the matching rows.",
        '=DSUM(A1:E20, "Profit", G1:H2)',
    ],
    DVAR: [
        DATABASE_ARGS,
        "Estimates the sample variance of the matching rows.",
        '=DVAR(A1:E20, "Yield", G1:H2)',
    ],
    DVARP: [
        DATABASE_ARGS,
        "Returns the population variance of the matching rows.",
        '=DVARP(A1:E20, "Yield", G1:H2)',
    ],
};

function table(category: FunctionCategory, rows: Record<string, Row>): [string, FunctionDetail][] {
    return Object.entries(rows).map(([name, [signature, description, example, args]]) => [
        name,
        { category, signature, description, example, ...(args ? { args } : {}) },
    ]);
}

/** Reference details by function name (uppercase, without the `_xlfn.` prefix). */
export const FUNCTION_DETAILS: Record<string, FunctionDetail> = Object.fromEntries([
    ...table("Math & trig", MATH),
    ...table("Statistical", STATISTICAL),
    ...table("Logical", LOGICAL),
    ...table("Text", TEXT),
    ...table("Date & time", DATE_TIME),
    ...table("Lookup & reference", LOOKUP),
    ...table("Financial", FINANCIAL),
    ...table("Information", INFORMATION),
    ...table("Engineering", ENGINEERING),
    ...table("Database", DATABASE),
]);
